#!/usr/bin/env python3
"""Auto-generated by FlowCast — run to replay all steps without recording."""
from __future__ import annotations
import sys
from pathlib import Path

# Allow running from the output directory
sys.path.insert(0, str(Path(__file__).parent.parent.parent))

from dotenv import load_dotenv
load_dotenv()

from src import runner


def _run(action):
    resolved = runner.resolve(action)
    if resolved.get('_skip'):
        return
    runner.fire(resolved)
    if resolved['action'] not in ('open_app', 'wait', 'hotkey'):
        runner.wait_ui_change()
    runner.wait_ui_settle()


# ──────────────────────────────────────────────────────────
# Step 1: Create a New Integration Project
# ──────────────────────────────────────────────────────────
_run({'action': 'open_app', 'app_name': 'WSO2 Integrator', 'app_path': '/Users/sachindu/Applications/WSO2 Integrator.app'})
_run({'action': 'click', 'target': 'Create'})
_run({'action': 'type', 'field_target': 'Integration Name', 'value': 'NewsAlertSystem'})
_run({'action': 'type', 'field_target': 'Project Name', 'value': 'NewsAlert'})
_run({'action': 'click', 'target': 'Browse'})
_run({'action': 'click', 'target': 'Open'})
_run({'action': 'click', 'target': 'Create Integration'})

# ──────────────────────────────────────────────────────────
# Step 2: Add an GraphQL Service Artifact
# ──────────────────────────────────────────────────────────
_run({'action': 'click', 'target': 'NewsAlertSystem'})
_run({'action': 'click', 'target': 'Add Artifact'})
_run({'action': 'click', 'target': 'GraphQL Service'})
_run({'action': 'type', 'field_target': 'Base Path', 'value': '/news'})
_run({'action': 'type', 'field_target': 'Port', 'value': '8080'})
_run({'action': 'click', 'target': 'Create'})

# ──────────────────────────────────────────────────────────
# Step 3: Configure the GraphQL Service Logic
# ──────────────────────────────────────────────────────────
_run({'action': 'click', 'target': '+', 'hint': 'next_to:Query'})

# ──────────────────────────────────────────────────────────
# Step 4: Create News Data Types
# ──────────────────────────────────────────────────────────

# ──────────────────────────────────────────────────────────
# Step 5: Create News Data Types
# ──────────────────────────────────────────────────────────
_run({'action': 'click', 'target': '+ Add Type'})
_run({'action': 'type', 'field_target': 'Kind', 'value': 'Record'})
_run({'action': 'type', 'field_target': 'Name', 'value': 'News'})
_run({'action': 'click', 'target': '+'})
_run({'action': 'type', 'field_target': 'Field Name', 'value': 'Headline'})
_run({'action': 'click', 'target': '+'})
_run({'action': 'type', 'field_target': 'Field Name', 'value': 'Content'})
_run({'action': 'click', 'target': 'Save'})

# ──────────────────────────────────────────────────────────
# Step 6: Define the allNews Query Operation
# ──────────────────────────────────────────────────────────
_run({'action': 'click', 'target': '+ Create Operations'})
_run({'action': 'click', 'target': '+', 'hint': 'next_to:Query'})
_run({'action': 'type', 'field_target': 'Field Name', 'value': 'allNews'})
_run({'action': 'type', 'field_target': 'Field Type', 'value': 'News[]'})
_run({'action': 'click', 'target': 'Save'})
_run({'action': 'click', 'target': '+'})
_run({'action': 'click', 'target': 'Return'})
_run({'action': 'type', 'field_target': 'Expression', 'value': 'newsStorage'})
_run({'action': 'click', 'target': 'Save'})

# ──────────────────────────────────────────────────────────
# Step 7: Define the publishNews Mutation
# ──────────────────────────────────────────────────────────
_run({'action': 'click', 'target': '+', 'hint': 'next_to:Mutation'})
_run({'action': 'type', 'field_target': 'Field Name', 'value': 'publishNews'})
_run({'action': 'click', 'target': '+ Add Argument'})
_run({'action': 'type', 'field_target': 'Argument Type', 'value': 'string'})
_run({'action': 'click', 'target': 'Add'})
_run({'action': 'click', 'target': '+ Add Argument'})
_run({'action': 'type', 'field_target': 'Argument Type', 'value': 'string'})
_run({'action': 'click', 'target': 'Add'})
_run({'action': 'type', 'field_target': 'Field Type', 'value': 'News'})
_run({'action': 'click', 'target': 'Save'})

# ──────────────────────────────────────────────────────────
# Step 8: Implement the publishNews Mutation Logic
# ──────────────────────────────────────────────────────────
_run({'action': 'click', 'target': '+'})
_run({'action': 'click', 'target': 'Declare Variable'})
_run({'action': 'type', 'field_target': 'Name', 'value': 'newNews'})
_run({'action': 'click', 'target': 'Expression'})
_run({'action': 'click', 'target': 'Record Configuration'})
_run({'action': 'click', 'target': 'Save'})
_run({'action': 'click', 'target': '+'})
_run({'action': 'click', 'target': 'Return'})
_run({'action': 'type', 'field_target': 'Expression', 'value': 'newNews'})
_run({'action': 'click', 'target': 'Save'})

# ──────────────────────────────────────────────────────────
# Step 9: Complete the Mutation Logic in Code
# ──────────────────────────────────────────────────────────
_run({'action': 'click', 'target': 'Save'})

# ──────────────────────────────────────────────────────────
# Step 10: Create the NewsGenerator Service Class
# ──────────────────────────────────────────────────────────
_run({'action': 'click', 'target': '+ Add Type'})
_run({'action': 'type', 'field_target': 'Kind', 'value': 'Service Class'})
_run({'action': 'type', 'field_target': 'Name', 'value': 'NewsGenerator'})
_run({'action': 'click', 'target': 'Save'})
_run({'action': 'click', 'target': '+ Variable'})
_run({'action': 'type', 'field_target': 'Variable Name', 'value': 'newsItems'})
_run({'action': 'click', 'target': 'Save'})
_run({'action': 'click', 'target': '+ Method'})
_run({'action': 'click', 'target': 'Remote'})
_run({'action': 'type', 'field_target': 'Function Name', 'value': 'next'})
_run({'action': 'type', 'field_target': 'Return Type', 'value': 'record {| News value; |}|error?'})
_run({'action': 'click', 'target': 'Save'})

# ──────────────────────────────────────────────────────────
# Step 11: Finalize the Service Class in Code
# ──────────────────────────────────────────────────────────
_run({'action': 'click', 'target': 'Save'})

# ──────────────────────────────────────────────────────────
# Step 12: Implement the NewsGenerator Stream Logic
# ──────────────────────────────────────────────────────────
_run({'action': 'click', 'target': '+'})
_run({'action': 'click', 'target': 'If'})
_run({'action': 'type', 'field_target': 'Condition', 'value': 'self.newsItems.length() == 0'})
_run({'action': 'click', 'target': 'Save'})
_run({'action': 'click', 'target': '+'})
_run({'action': 'click', 'target': 'Return'})
_run({'action': 'type', 'field_target': 'Expression', 'value': '()'})
_run({'action': 'click', 'target': 'Save'})

# ──────────────────────────────────────────────────────────
# Step 13: Implement the Stream Iteration Logic
# ──────────────────────────────────────────────────────────
_run({'action': 'click', 'target': '+'})
_run({'action': 'click', 'target': 'Call Function'})
_run({'action': 'type', 'field_target': 'Seconds', 'value': '2'})
_run({'action': 'click', 'target': 'Save'})
_run({'action': 'click', 'target': '+'})
_run({'action': 'click', 'target': 'Declare Variable'})
_run({'action': 'type', 'field_target': 'Name', 'value': 'currentNews'})
_run({'action': 'type', 'field_target': 'Expression', 'value': 'self.newsItems.shift()'})
_run({'action': 'click', 'target': 'Save'})
_run({'action': 'click', 'target': '+'})
_run({'action': 'click', 'target': 'Return'})
_run({'action': 'type', 'field_target': 'Expression', 'value': '{value: currentNews}'})
_run({'action': 'click', 'target': 'Save'})

# ──────────────────────────────────────────────────────────
# Step 14: Define the GraphQL Subscription Operation
# ──────────────────────────────────────────────────────────
_run({'action': 'click', 'target': '+', 'hint': 'next_to:Subscription'})
_run({'action': 'type', 'field_target': 'Field Name', 'value': 'generateNews'})
_run({'action': 'type', 'field_target': 'Field Type', 'value': 'stream'})
_run({'action': 'click', 'target': 'Save'})

# ──────────────────────────────────────────────────────────
# Step 15: Finalize the Subscription Implementation in Code
# ──────────────────────────────────────────────────────────
_run({'action': 'click', 'target': 'Save'})

# ──────────────────────────────────────────────────────────
# Step 16: Run and Test the Service
# ──────────────────────────────────────────────────────────
_run({'action': 'click', 'target': 'Run'})
_run({'action': 'click', 'target': 'Test'})
