#!/usr/bin/env python3
"""Auto-generated by FlowCast — run to replay all steps without recording."""
from __future__ import annotations
import sys
from pathlib import Path

# Allow running from the output directory
sys.path.insert(0, str(Path(__file__).parent.parent.parent))

from dotenv import load_dotenv
load_dotenv()

from src import runner


def _run(action):
    resolved = runner.resolve(action)
    if resolved.get('_skip'):
        return
    runner.fire(resolved)
    if resolved['action'] not in ('open_app', 'wait', 'hotkey'):
        runner.wait_ui_change()
    runner.wait_ui_settle()


# ──────────────────────────────────────────────────────────
# Step 1: Create a New Integration Project
# ──────────────────────────────────────────────────────────
_run({'action': 'open_app', 'app_name': 'WSO2 Integrator', 'app_path': '/Users/sachindu/Applications/WSO2 Integrator.app'})
_run({'action': 'click', 'target': 'Create'})
_run({'action': 'type', 'field_target': 'Integration Name', 'value': 'OrderProcessor'})
_run({'action': 'type', 'field_target': 'Project Name', 'value': 'Quick_Start'})
_run({'action': 'click', 'target': 'Browse'})
_run({'action': 'click', 'target': 'Open'})
_run({'action': 'click', 'target': 'Create Integration'})

# ──────────────────────────────────────────────────────────
# Step 2: Add a RabbitMQ Event Integration Artifact
# ──────────────────────────────────────────────────────────
_run({'action': 'click', 'target': 'OrderProcessor'})
_run({'action': 'click', 'target': 'Add Artifact'})
_run({'action': 'click', 'target': 'RabbitMQ'})

# ──────────────────────────────────────────────────────────
# Step 3: Configure the RabbitMQ Connection
# ──────────────────────────────────────────────────────────
_run({'action': 'type', 'field_target': 'Queue Name', 'value': 'Orders'})
_run({'action': 'type', 'field_target': 'Host', 'value': 'localhost'})
_run({'action': 'type', 'field_target': 'Port', 'value': '5672'})
_run({'action': 'click', 'target': 'Create'})

# ──────────────────────────────────────────────────────────
# Step 4: Add Message Processing Logic
# ──────────────────────────────────────────────────────────
_run({'action': 'click', 'target': '+ Add Handler'})
_run({'action': 'click', 'target': 'onMessage'})
_run({'action': 'click', 'target': 'Save'})
_run({'action': 'click', 'target': '+'})
_run({'action': 'click', 'target': 'Call Function'})
_run({'action': 'click', 'target': 'printInfo'})
_run({'action': 'type', 'field_target': 'Msg', 'value': 'Received order'})
_run({'action': 'click', 'target': 'Save'})

# ──────────────────────────────────────────────────────────
# Step 5: Run and Test the Integration
# ──────────────────────────────────────────────────────────
_run({'action': 'click', 'target': 'Run'})
