#!/usr/bin/env python3
"""Auto-generated by FlowCast — run to replay all steps without recording."""
from __future__ import annotations
import sys
from pathlib import Path

# Allow running from the output directory
sys.path.insert(0, str(Path(__file__).parent.parent.parent))

from dotenv import load_dotenv
load_dotenv()

from src import runner


def _run(action):
    resolved = runner.resolve(action)
    if resolved.get('_skip'):
        return
    runner.fire(resolved)
    if resolved['action'] not in ('open_app', 'wait', 'hotkey'):
        runner.wait_ui_change()
    runner.wait_ui_settle()


# ──────────────────────────────────────────────────────────
# Step 1: Create the Project
# ──────────────────────────────────────────────────────────
_run({'action': 'open_app', 'app_name': 'WSO2 Integrator', 'app_path': '/Users/sachindu/Applications/WSO2 Integrator.app'})
_run({'action': 'click', 'target': 'Create'})
_run({'action': 'type', 'field_target': 'Integration Name', 'value': 'InventoryService'})
_run({'action': 'type', 'field_target': 'Project Name', 'value': 'Quick_Start'})
_run({'action': 'click', 'target': 'Browse'})
_run({'action': 'click', 'target': 'Open'})
_run({'action': 'click', 'target': 'Create Integration'})

# ──────────────────────────────────────────────────────────
# Step 2: Initialize Database Connection
# ──────────────────────────────────────────────────────────
_run({'action': 'click', 'target': 'InventoryService'})
_run({'action': 'click', 'target': '+ Add Artifact'})
_run({'action': 'scroll', 'clicks': -15})
_run({'action': 'click', 'target': 'Connection'})
_run({'action': 'click', 'target': 'Connect to a Database'})

# ──────────────────────────────────────────────────────────
# Step 3: Configure Database Settings
# ──────────────────────────────────────────────────────────
_run({'action': 'type', 'field_target': 'Host', 'value': 'localhost'})
_run({'action': 'type', 'field_target': 'Port', 'value': '3306'})
_run({'action': 'type', 'field_target': 'Database', 'value': 'simple_db'})
_run({'action': 'type', 'field_target': 'User', 'value': 'start'})
_run({'action': 'type', 'field_target': 'Password', 'value': 'start'})
_run({'action': 'click', 'target': 'Connect & Introspect Database'})
_run({'action': 'click', 'target': 'inventory'})
_run({'action': 'click', 'target': 'Continue to Connection Details'})
_run({'action': 'type', 'field_target': 'Connection Name', 'value': 'inventoryDB'})
_run({'action': 'click', 'target': 'Save Connection'})

# ──────────────────────────────────────────────────────────
# Step 4: Bootstrap Automation Flow
# ──────────────────────────────────────────────────────────
_run({'action': 'click', 'target': 'InventoryService'})
_run({'action': 'click', 'target': '+ Add Artifact'})
_run({'action': 'click', 'target': 'Automation'})
_run({'action': 'click', 'target': 'Create'})
_run({'action': 'click', 'target': '+'})

# ──────────────────────────────────────────────────────────
# Step 5: Configure Data Selection
# ──────────────────────────────────────────────────────────
_run({'action': 'click', 'target': 'inventoryDB'})
_run({'action': 'click', 'target': 'Get rows from inventory table'})
_run({'action': 'type', 'field_target': 'Result', 'value': 'ItemsNames'})
_run({'action': 'click', 'target': 'ItemName'})
_run({'action': 'click', 'target': 'Save'})

# ──────────────────────────────────────────────────────────
# Step 6: Implement Logic Loop
# ──────────────────────────────────────────────────────────
_run({'action': 'click', 'target': '+'})
_run({'action': 'search', 'field_target': 'Search', 'value': 'println'})
_run({'action': 'click', 'target': 'println'})
_run({'action': 'click', 'target': 'Initialize Array'})
_run({'action': 'type', 'field_target': 'Values', 'value': 'itemsNames'})
_run({'action': 'click', 'target': 'Save'})

# ──────────────────────────────────────────────────────────
# Step 7: Run and Test
# ──────────────────────────────────────────────────────────
_run({'action': 'click', 'target': 'Run'})
