#!/usr/bin/env python3
"""Auto-generated by FlowCast — run to replay all steps without recording."""
from __future__ import annotations
import sys
from pathlib import Path

# Allow running from the output directory
sys.path.insert(0, str(Path(__file__).parent.parent.parent))

from dotenv import load_dotenv
load_dotenv()

from src import runner


def _run(action):
    resolved = runner.resolve(action)
    if resolved.get('_skip'):
        return
    runner.fire(resolved)
    if resolved['action'] not in ('open_app', 'wait', 'hotkey'):
        runner.wait_ui_change()
    runner.wait_ui_settle()


# ──────────────────────────────────────────────────────────
# Step 1: Create the Project
# ──────────────────────────────────────────────────────────
_run({'action': 'open_app', 'app_name': 'WSO2 Integrator', 'app_path': '/Users/sachindu/Applications/WSO2 Integrator.app'})
_run({'action': 'click', 'target': 'Create'})
_run({'action': 'type', 'field_target': 'Integration Name', 'value': 'AI Agent'})
_run({'action': 'type', 'field_target': 'Project Name', 'value': 'Quick_Start'})
_run({'action': 'click', 'target': 'Browse'})
_run({'action': 'click', 'target': 'Open'})
_run({'action': 'click', 'target': 'Create Integration'})

# ──────────────────────────────────────────────────────────
# Step 2: Add a File Integration Artifact
# ──────────────────────────────────────────────────────────
_run({'action': 'click', 'target': 'AI Agent'})
_run({'action': 'click', 'target': '+ Add Artifact'})
_run({'action': 'scroll', 'clicks': -5})
_run({'action': 'click', 'target': 'AI Chat Agent'})
_run({'action': 'type', 'field_target': 'Name', 'value': 'Wso2 Integrator Assistant'})
_run({'action': 'click', 'target': 'Create'})

# ──────────────────────────────────────────────────────────
# Step 3: Configure the AI Agent
# ──────────────────────────────────────────────────────────
_run({'action': 'click', 'target': 'Wso2 Integrator Assistant'})
_run({'action': 'type', 'field_target': 'Instructions', 'value': 'You are a highly skilled WSO2 Integration Architect. Your goal is to assist developers in building, debugging, and optimizing integration flows.'})
_run({'action': 'click', 'target': 'Save'})

# ──────────────────────────────────────────────────────────
# Step 4: Run and test
# ──────────────────────────────────────────────────────────
_run({'action': 'click', 'target': 'Run'})
_run({'action': 'click', 'target': 'Chat'})
