#!/usr/bin/env python3
"""Auto-generated by FlowCast — run to replay all steps without recording."""
from __future__ import annotations
import sys
from pathlib import Path

# Allow running from the output directory
sys.path.insert(0, str(Path(__file__).parent.parent.parent))

from dotenv import load_dotenv
load_dotenv()

from src import runner


def _run(action):
    resolved = runner.resolve(action)
    if resolved.get('_skip'):
        return
    runner.fire(resolved)
    if resolved['action'] not in ('open_app', 'wait', 'hotkey'):
        runner.wait_ui_change()
    runner.wait_ui_settle()


# ──────────────────────────────────────────────────────────
# Step 1: Create the Project
# ──────────────────────────────────────────────────────────
_run({'action': 'open_app', 'app_name': 'WSO2 Integrator', 'app_path': '/Users/sachindu/Applications/WSO2 Integrator.app'})
_run({'action': 'click', 'target': 'Create'})
_run({'action': 'type', 'field_target': 'Integration Name', 'value': 'FileTracker'})
_run({'action': 'type', 'field_target': 'Project Name', 'value': 'Quick_Start'})
_run({'action': 'click', 'target': 'Browse'})
_run({'action': 'click', 'target': 'Open'})
_run({'action': 'click', 'target': 'Create Integration'})

# ──────────────────────────────────────────────────────────
# Step 2: Add a File Integration Artifact
# ──────────────────────────────────────────────────────────
_run({'action': 'click', 'target': 'FileTracker'})
_run({'action': 'click', 'target': '+ Add Artifact'})
_run({'action': 'scroll', 'clicks': -5})
_run({'action': 'click', 'target': 'Local Files'})
_run({'action': 'type', 'field_target': 'Path', 'value': '"/tmp"'})
_run({'action': 'click', 'target': 'Create'})

# ──────────────────────────────────────────────────────────
# Step 3: Tracking modified files
# ──────────────────────────────────────────────────────────
_run({'action': 'click', 'target': 'Add Handler'})
_run({'action': 'click', 'target': 'onModify'})
_run({'action': 'click', 'target': 'onModify'})
_run({'action': 'click', 'target': '+'})
_run({'action': 'search', 'field_target': 'Search', 'value': 'printInfo'})
_run({'action': 'click', 'target': 'printInfo'})
_run({'action': 'type', 'field_target': 'Msg', 'value': 'File modified'})
_run({'action': 'click', 'target': 'Save'})

# ──────────────────────────────────────────────────────────
# Step 4: Run and Test
# ──────────────────────────────────────────────────────────
_run({'action': 'click', 'target': 'Run', 'post_delay': 5.0})
_run({'action': 'wait', 'seconds': 5.0})
