#!/usr/bin/env python3
"""
Auto-generated PyAutoGUI replay script: create-automation
Generated by FlowCast codegen.

Run with:
    python create-automation.py

Requires: pip install pyautogui
Note: Screen coordinates are hardcoded from the original recording.
"""
import subprocess
import time

import pyautogui

pyautogui.FAILSAFE = True
pyautogui.PAUSE = 0.3
pyautogui.MINIMUM_DURATION = 0.3


def main():
    print("Starting replay: create-automation")
    print("Move mouse to top-left corner to abort (failsafe)")
    time.sleep(2)  # Grace period before starting

    # Action 1: click
    print("Clicking 'Add Artifact' at (651, 542)")
    pyautogui.click(651, 542, duration=0.4)
    time.sleep(1.0)
    # Action 2: click
    print("Clicking 'Automation' at (360, 328)")
    pyautogui.click(360, 328, duration=0.4)
    time.sleep(1.0)
    # Action 3: click
    print("Clicking 'Create' at (361, 250)")
    pyautogui.click(361, 250, duration=0.4)
    time.sleep(1.0)
    # Action 4: click
    print("Clicking '+' at (874, 501)")
    pyautogui.click(874, 501, duration=0.4)
    time.sleep(1.0)
    # Action 5: click
    print("Clicking 'Call Function' at (1220, 426)")
    pyautogui.click(1220, 426, duration=0.4)
    time.sleep(1.0)
    # Action 6: click
    print("Clicking 'println' at (1191, 568)")
    pyautogui.click(1191, 568, duration=0.4)
    time.sleep(1.0)
    # Action 7: click
    print("Clicking 'Initialize Array' at (1199, 300)")
    pyautogui.click(1199, 300, duration=0.4)
    time.sleep(1.0)
    # Action 8: click
    print("Clicking 'Fx' at (1156, 315)")
    pyautogui.click(1156, 315, duration=0.4)
    time.sleep(1.0)
    # Action 9: type
    print("Typing \"expression input\" into \"Fx\"")
    pyautogui.click(1146, 314, clicks=3, interval=0.1)
    time.sleep(0.3)
    subprocess.run(["pbcopy"], input="expression input".encode(), check=True)
    pyautogui.hotkey('command', 'v')
    time.sleep(1.0)
    # Action 10: click
    print("Clicking 'Save' at (1468, 416)")
    pyautogui.click(1468, 416, duration=0.4)
    time.sleep(1.0)

    print("Replay complete: create-automation")


if __name__ == "__main__":
    main()
