#!/usr/bin/env python3
"""
Auto-generated PyAutoGUI replay script: create-integration-project
Generated by FlowCast codegen.

Run with:
    python create-integration-project.py

Requires: pip install pyautogui
Note: Screen coordinates are hardcoded from the original recording.
"""
import subprocess
import time

import pyautogui

pyautogui.FAILSAFE = True
pyautogui.PAUSE = 0.3
pyautogui.MINIMUM_DURATION = 0.3


def main():
    print("Starting replay: create-integration-project")
    print("Move mouse to top-left corner to abort (failsafe)")
    time.sleep(2)  # Grace period before starting

    # Action 1: shell
    print("Running: open \"$HOME/Applications/WSO2 Integrator.app\"")
    subprocess.run("open \"$HOME/Applications/WSO2 Integrator.app\"", shell=True, check=True)
    time.sleep(8)
    # Action 2: shell
    print("Running: osascript -e 'tell application \"WSO2 Integrator\" to activa")
    subprocess.run("osascript -e 'tell application \"WSO2 Integrator\" to activate' -e 'delay 1' -e 'tell application \"Finder\" to set _b to bounds of window of desktop' -e 'tell application \"System Events\" to tell process \"WSO2 Integrator\"' -e '  set position of window 1 to {0, 25}' -e '  set size of window 1 to {item 3 of _b, (item 4 of _b) - 25}' -e 'end tell'", shell=True, check=True)
    time.sleep(2)
    # Action 3: click
    print("Clicking 'Get Started' at (112, 91)")
    pyautogui.click(112, 91, duration=0.4)
    time.sleep(1.0)
    # Action 4: click
    print("Clicking 'Create' at (129, 548)")
    pyautogui.click(129, 548, duration=0.4)
    time.sleep(1.0)
    # Action 5: type
    print("Typing \"Create Hello World Automation\" into \"Integration Name\"")
    pyautogui.click(510, 312, clicks=3, interval=0.1)
    time.sleep(0.3)
    subprocess.run(["pbcopy"], input="Create Hello World Automation".encode(), check=True)
    pyautogui.hotkey('command', 'v')
    time.sleep(1.0)
    # Action 6: click
    print("Clicking 'Browse' at (1013, 488)")
    pyautogui.click(1013, 488, duration=0.4)
    time.sleep(1.0)
    # Action 7: click
    print("Clicking 'Open' at (1138, 699)")
    pyautogui.click(1138, 699, duration=0.4)
    time.sleep(1.0)
    # Action 8: click
    print("Clicking 'Create Integration' at (988, 757)")
    pyautogui.click(988, 757, duration=0.4)
    time.sleep(1.0)

    print("Replay complete: create-integration-project")


if __name__ == "__main__":
    main()
