#!/usr/bin/env python3
"""
Auto-generated PyAutoGUI replay script: design-automation
Generated by FlowCast codegen.

Run with:
    python design-automation.py

Requires: pip install pyautogui
Note: Screen coordinates are hardcoded from the original recording.
"""
import subprocess
import time

import pyautogui

pyautogui.FAILSAFE = True
pyautogui.PAUSE = 0.3
pyautogui.MINIMUM_DURATION = 0.3


def main():
    print("Starting replay: design-automation")
    print("Move mouse to top-left corner to abort (failsafe)")
    time.sleep(2)  # Grace period before starting

    # Action 1: shell
    print("Running: open \"$HOME/Applications/WSO2 Integrator.app\"")
    subprocess.run("open \"$HOME/Applications/WSO2 Integrator.app\"", shell=True, check=True)
    time.sleep(8)
    # Action 2: shell
    print("Running: osascript -e 'tell application \"WSO2 Integrator\" to activa")
    subprocess.run("osascript -e 'tell application \"WSO2 Integrator\" to activate' -e 'delay 1' -e 'tell application \"Finder\" to set _b to bounds of window of desktop' -e 'tell application \"System Events\" to tell process \"WSO2 Integrator\"' -e '  set position of window 1 to {0, 25}' -e '  set size of window 1 to {item 3 of _b, (item 4 of _b) - 25}' -e 'end tell'", shell=True, check=True)
    time.sleep(2)
    # Action 3: click
    print("Clicking 'Add Artifact' at (651, 542)")
    pyautogui.click(651, 542, duration=0.4)
    time.sleep(1.0)
    # Action 4: click
    print("Clicking 'Automation' at (360, 328)")
    pyautogui.click(360, 328, duration=0.4)
    time.sleep(1.0)
    # Action 5: click
    print("Clicking 'Create' at (361, 250)")
    pyautogui.click(361, 250, duration=0.4)
    time.sleep(1.0)
    # Action 6: click
    print("Clicking '+' at (874, 501)")
    pyautogui.click(874, 501, duration=0.4)
    time.sleep(1.0)
    # Action 7: click
    print("Clicking 'Call Function' at (1220, 426)")
    pyautogui.click(1220, 426, duration=0.4)
    time.sleep(1.0)
    # Action 8: click
    print("Clicking 'println' at (1191, 568)")
    pyautogui.click(1191, 568, duration=0.4)
    time.sleep(1.0)
    # Action 9: click
    print("Clicking 'Initialize Array' at (1199, 300)")
    pyautogui.click(1199, 300, duration=0.4)
    time.sleep(1.0)
    # Action 10: click
    print("Clicking 'Fx' at (1346, 315)")
    pyautogui.click(1346, 315, duration=0.4)
    time.sleep(1.0)
    # Action 11: type
    print("Typing \"\"Hello World\"\" into focused field")
    subprocess.run(["pbcopy"], input="\"Hello World\"".encode(), check=True)
    pyautogui.hotkey('command', 'v')
    time.sleep(1.0)
    # Action 12: click
    print("Clicking 'Save' at (1468, 416)")
    pyautogui.click(1468, 416, duration=0.4)
    time.sleep(1.0)

    print("Replay complete: design-automation")


if __name__ == "__main__":
    main()
