#!/usr/bin/env python3
"""
Auto-generated PyAutoGUI replay script: run-automation
Generated by FlowCast codegen.

Run with:
    python run-automation.py

Requires: pip install pyautogui
Note: Screen coordinates are hardcoded from the original recording.
"""
import subprocess
import time

import pyautogui

pyautogui.FAILSAFE = True
pyautogui.PAUSE = 0.3
pyautogui.MINIMUM_DURATION = 0.3


def main():
    print("Starting replay: run-automation")
    print("Move mouse to top-left corner to abort (failsafe)")
    time.sleep(2)  # Grace period before starting

    # Action 1: click
    print("Clicking 'Run' at (1383, 85)")
    pyautogui.click(1383, 85, duration=0.4)
    time.sleep(1.0)

    print("Replay complete: run-automation")


if __name__ == "__main__":
    main()
