#!/usr/bin/env python3
"""Auto-generated by FlowCast — run to replay all steps without recording."""
from __future__ import annotations
import sys
from pathlib import Path

# Allow running from the output directory
sys.path.insert(0, str(Path(__file__).parent.parent.parent))

from dotenv import load_dotenv
load_dotenv()

from src import runner


def _run(action):
    resolved = runner.resolve(action)
    if resolved.get('_skip'):
        return
    runner.fire(resolved)
    if resolved['action'] not in ('open_app', 'wait', 'hotkey'):
        runner.wait_ui_change()
    runner.wait_ui_settle()


# ──────────────────────────────────────────────────────────
# Step 1: Create the project
# ──────────────────────────────────────────────────────────
_run({'action': 'open_app', 'app_name': 'WSO2 Integrator', 'app_path': '/Users/sachindu/Applications/WSO2 Integrator.app'})
_run({'action': 'click', 'target': 'Create'})
_run({'action': 'type', 'field_target': 'Integration Name', 'value': 'Integration'})
_run({'action': 'click', 'target': 'Browse'})
_run({'action': 'click', 'target': 'Open'})
_run({'action': 'click', 'target': 'Create Integration'})

# ──────────────────────────────────────────────────────────
# Step 2: Add an automation artifact
# ──────────────────────────────────────────────────────────
<<<<<<< HEAD
_run({'action': 'click', 'target': 'Integration'})
=======
>>>>>>> 0f4bdc1 (Add dark and light renaming)
_run({'action': 'click', 'target': '+ Add Artifact'})
_run({'action': 'click', 'target': 'Automation'})
_run({'action': 'click', 'target': 'Create'})

# ──────────────────────────────────────────────────────────
# Step 3: Add logic
# ──────────────────────────────────────────────────────────
_run({'action': 'click', 'target': '+'})
_run({'action': 'click', 'target': 'Call Function'})
_run({'action': 'click', 'target': 'Println'})
_run({'action': 'click', 'target': 'Initialize Array'})
_run({'action': 'type', 'field_target': 'Values', 'value': '"Hello World"'})
_run({'action': 'click', 'target': 'Save'})

# ──────────────────────────────────────────────────────────
# Step 4: Run and test
# ──────────────────────────────────────────────────────────
_run({'action': 'click', 'target': 'Run'})
