#!/usr/bin/env python3
"""Auto-generated by FlowCast v2 — replays all steps via Playwright/CDP.

Requires VS Code running with --remote-debugging-port (the driver launches
it if needed). No recording, no narration — just the automation.
"""
from __future__ import annotations
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[3]))

from dotenv import load_dotenv
load_dotenv()

from v2.driver import Driver

driver = Driver()
driver.connect()

def _run(action):
    print(f"  -> {action}")
    driver.execute(action)
    driver.wait_settle()


# ──────────────────────────────────────────────────────────
# Step 1: Create the project
# ──────────────────────────────────────────────────────────
print('Step 1: Create the project')
_run({'action': 'click', 'target': 'Skip for now'})
_run({'action': 'wait', 'seconds': 3, 'reason': 'Wait for workbench to load after skip'})
_run({'action': 'hotkey', 'keys': 'Meta+Shift+P'})
_run({'action': 'type', 'target': '', 'value': 'WSO2 Integrator: Open Welcome Page'})
_run({'action': 'hotkey', 'keys': 'Enter'})
_run({'action': 'wait', 'seconds': 10, 'reason': 'Welcome page loads in webview'})
_run({'action': 'click', 'target': '**Create**'})
_run({'action': 'type', 'target': '**Integration Name**', 'value': 'HelloWorld'})
_run({'action': 'type', 'target': '**Project Name**', 'value': 'QuickStart'})
_run({'action': 'click', 'target': '**Browse**'})
_run({'action': 'wait', 'seconds': 3, 'reason': '...'})
_run({'action': 'click', 'target': '**Open**'})
_run({'action': 'click', 'target': '**Create Integration**'})

# ──────────────────────────────────────────────────────────
# Step 2: Add an automation artifact
# ──────────────────────────────────────────────────────────
print('Step 2: Add an automation artifact')
_run({'action': 'click', 'target': '**Get Started**'})
_run({'action': 'click', 'target': '**+ Add Artifact**'})
_run({'action': 'select', 'target': '**Automation** artifact'})
_run({'action': 'click', 'target': '**Create**'})

# ──────────────────────────────────────────────────────────
# Step 3: Add logic
# ──────────────────────────────────────────────────────────
print('Step 3: Add logic')
_run({'action': 'click', 'target': '**+** after the **Start** node', 'hint': 'in the graph'})
_run({'action': 'wait', 'seconds': 2, 'reason': '...panel opens'})
_run({'action': 'type', 'target': '', 'value': 'Println'})
_run({'action': 'hotkey', 'keys': 'Enter'})
_run({'action': 'click', 'target': '**Println**'})
_run({'action': 'wait', 'seconds': 2, 'reason': '...panel opens'})
_run({'action': 'type', 'target': '', 'value': 'Initialize Array'})
_run({'action': 'hotkey', 'keys': 'Enter'})
_run({'action': 'click', 'target': '**Println**'})
_run({'action': 'wait', 'seconds': 2, 'reason': '...panel opens'})
_run({'action': 'type', 'target': '', 'value': 'Hello World'})
_run({'action': 'hotkey', 'keys': 'Tab'})
_run({'action': 'type', 'target': '**Values**', 'value': ''})
_run({'action': 'click', 'target': '**Save**'})

# ──────────────────────────────────────────────────────────
# Step 4: Run and test
# ──────────────────────────────────────────────────────────
print('Step 4: Run and test')
_run({'action': 'click', 'target': '**Run**'})
_run({'action': 'wait', 'seconds': 1, 'reason': '...'})
_run({'action': 'wait', 'seconds': 3, 'reason': '...'})
_run({'action': 'wait', 'seconds': 3, 'reason': '...'})

driver.close()
print('Replay complete.')