#!/usr/bin/env python3
"""Auto-generated by FlowCast — run to replay all steps without recording."""
from __future__ import annotations
import sys
from pathlib import Path

# Allow running from the output directory
sys.path.insert(0, str(Path(__file__).parent.parent.parent))

from dotenv import load_dotenv
load_dotenv()

from src import runner


def _run(action):
    resolved = runner.resolve(action)
    if resolved.get('_skip'):
        return
    runner.fire(resolved)
    if resolved['action'] not in ('open_app', 'wait', 'hotkey'):
        runner.wait_ui_change()
    runner.wait_ui_settle()


# ──────────────────────────────────────────────────────────
# Step 1: Create the project
# ──────────────────────────────────────────────────────────
_run({'action': 'open_app', 'app_name': 'WSO2 Integrator', 'app_path': '/Users/sachindu/Applications/WSO2 Integrator.app'})
<<<<<<< HEAD
_run({'action': 'click', 'target': 'Create'})
_run({'action': 'type', 'field_target': 'Integration Name', 'value': 'Hello_World_API'})
=======
_run({'action': 'click', 'target': 'Create New Integration'})
<<<<<<< HEAD
_run({'action': 'type', 'field_target': 'Integration Name', 'value': 'HelloWorld'})
>>>>>>> 7d1f240 (improved text files)
=======
_run({'action': 'type', 'field_target': 'Integration Name', 'value': 'Hello_World_API'})
>>>>>>> f89df14 (ffmpeg)
_run({'action': 'click', 'target': 'Browse'})
_run({'action': 'click', 'target': 'Open'})
_run({'action': 'click', 'target': 'Create Integration'})

# ──────────────────────────────────────────────────────────
# Step 2: Add an HTTP service
# ──────────────────────────────────────────────────────────
_run({'action': 'click', 'target': 'Add Artifact'})
_run({'action': 'click', 'target': 'HTTP Service'})
_run({'action': 'type', 'field_target': 'Service Base Path', 'value': '/hello'})
_run({'action': 'click', 'target': 'Create'})

# ──────────────────────────────────────────────────────────
# Step 3: Design the integration flow
# ──────────────────────────────────────────────────────────
<<<<<<< HEAD
<<<<<<< HEAD
_run({'action': 'click', 'target': '+ Add Resouses'})
_run({'action': 'click', 'target': 'GET'})
_run({'action': 'type', 'field_target': 'Resource Path', 'value': 'greeting'})
_run({'action': 'click', 'target': 'Save'})
<<<<<<< HEAD
_run({'action': 'click', 'target': '+'})
_run({'action': 'click', 'target': 'Add Connection'})
_run({'action': 'click', 'target': 'HTTP'})

# ──────────────────────────────────────────────────────────
# Step 4: Configure HTTP
# ──────────────────────────────────────────────────────────
_run({'action': 'type', 'field_target': 'Url', 'value': 'https://apis.wso2.com/zvdz/mi-qsg/v1.0'})
_run({'action': 'type', 'field_target': 'Connection Name', 'value': 'externalApi'})
_run({'action': 'click', 'target': 'Save Connection'})
_run({'action': 'click', 'target': 'externalApi'})
_run({'action': 'click', 'target': 'GET'})
_run({'action': 'type', 'field_target': 'Path', 'value': '/'})
_run({'action': 'type', 'field_target': 'Result', 'value': 'response'})
_run({'action': 'click', 'target': 'Save'})
_run({'action': 'click', 'target': '+'})
_run({'action': 'click', 'target': 'Return'})
_run({'action': 'type', 'field_target': 'Return expression', 'value': 'response'})
_run({'action': 'click', 'target': 'Save'})
=======
_run({'action': 'type', 'field_target': 'Resource path', 'value': '/greeting'})
=======
_run({'action': 'click', 'target': '+ Add Resouses'})
_run({'action': 'click', 'target': 'GET'})
_run({'action': 'type', 'field_target': 'Resource Path', 'value': 'greeting'})
>>>>>>> b856107 (1.0)
_run({'action': 'hotkey', 'keys': ['command', 's']})
=======
>>>>>>> f89df14 (ffmpeg)
_run({'action': 'click', 'target': '+'})
_run({'action': 'click', 'target': 'Add Connection'})
_run({'action': 'click', 'target': 'HTTP'})

# ──────────────────────────────────────────────────────────
# Step 4: Configure HTTP
# ──────────────────────────────────────────────────────────
_run({'action': 'type', 'field_target': 'Url', 'value': 'https://apis.wso2.com/zvdz/mi-qsg/v1.0'})
_run({'action': 'type', 'field_target': 'Connection Name', 'value': 'externalApi'})
_run({'action': 'click', 'target': 'Save Connection'})
_run({'action': 'click', 'target': 'get'})
_run({'action': 'type', 'field_target': 'Path', 'value': '/'})
_run({'action': 'type', 'field_target': 'Response Variable', 'value': 'response'})
_run({'action': 'select', 'field_target': 'Response Type', 'value': 'json'})
_run({'action': 'type', 'field_target': 'Return expression', 'value': 'response'})
>>>>>>> 7d1f240 (improved text files)
