"""Shared output builders used by both a normal run (main.py) and guide mode
(src/guide.py) so a workflow authored interactively produces the exact same
artifacts as one authored by hand and executed normally:

  step-NN-<slug>-<theme>.gif / .mov   — per-step recording
  full-<theme>.mov                    — all steps concatenated
  full_script-<theme>.py              — runnable replay script
  index.md                            — themed (light/dark) markdown for docs

Kept separate from main.py (rather than imported from it) so src/guide.py can
use these without importing the CLI entry-point module.
"""
from __future__ import annotations

import re
from pathlib import Path

from src.parser import Step
from src import recorder


def slug(text: str) -> str:
    return re.sub(r'[^a-z0-9]+', '-', text.lower()).strip('-')


def build_full_video(out_dir: Path, theme: str) -> Path | None:
    """Combine all existing step MOVs (sorted by step number) into full.mov."""
    step_movs = sorted(out_dir.glob(f"step-*-{theme}.mov"))
    if not step_movs:
        return None

    full_mov = out_dir / f"full-{theme}.mov"
    recorder.combine(step_movs, full_mov, keep_inputs=True)
    print(f"   Full video → {full_mov}")
    return full_mov


def build_themed_markdown(steps: list[Step], out_dir: Path, wf_slug: str) -> Path:
    """Generate a markdown file with <ThemedImage> components linking light/dark GIFs."""
    lines = []
    for idx, step in enumerate(steps, 1):
        lines.append(f"## Step {idx}: {step.title}")
        lines.append("")

        for instr in step.raw_instructions.splitlines():
            if instr.strip():
                lines.append(instr.strip())

        lines.append("")
        gif_stem = Path(step.gif_filename).stem

        themed_img = [
            "<ThemedImage",
            f'    alt="{step.title}"',
            "    sources={{",
            f"        light: useBaseUrl('/img/get-started/{wf_slug}/{gif_stem}-light.gif'),",
            f"        dark: useBaseUrl('/img/get-started/{wf_slug}/{gif_stem}-dark.gif'),",
            "    }}",
            "/>",
            ""
        ]
        lines.extend(themed_img)

    md_file = out_dir / "index.md"
    md_file.write_text("\n".join(lines))
    print(f"   Themed Markdown saved → {md_file}")
    return md_file


def build_full_script(steps: list[Step], out_dir: Path, theme: str) -> Path:
    """Write a runnable full_script.py containing all steps' actions."""
    lines = [
        "#!/usr/bin/env python3",
        '"""Auto-generated by FlowCast — run to replay all steps without recording."""',
        "from __future__ import annotations",
        "import sys",
        "from pathlib import Path",
        "",
        "# Allow running from the output directory",
        "sys.path.insert(0, str(Path(__file__).parent.parent.parent))",
        "",
        "from dotenv import load_dotenv",
        "load_dotenv()",
        "",
        "from src import runner",
        "",
        "# Always run the app full screen before making changes",
        "runner.ensure_fullscreen(force=True)",
        "",
        "",
        "def _run(action):",
        "    resolved = runner.resolve(action)",
        "    if resolved.get('_skip'):",
        "        return",
        "    runner.fire(resolved)",
        "    if resolved['action'] not in ('open_app', 'wait', 'hotkey'):",
        "        runner.wait_ui_change()",
        "    runner.wait_ui_settle()",
        "",
        "",
    ]

    for idx, step in enumerate(steps, 1):
        sep = "─" * 58
        lines.append(f"# {sep}")
        lines.append(f"# Step {idx}: {step.title}")
        lines.append(f"# {sep}")
        for action in step.actions:
            lines.append(f"_run({action!r})")
        lines.append("")

    script = out_dir / f"full_script-{theme}.py"
    script.write_text("\n".join(lines))
    print(f"   Script saved → {script}")
    return script
