"""
codegen.py — Generate standalone PyAutoGUI Python scripts from resolved actions.

After FlowCast runs a workflow and records GIFs, this module generates
a replay script with hardcoded coordinates so the workflow can be
re-executed without OCR/vision detection.

Usage:
    from src.codegen import generate_script
    script_path = generate_script(actions, output_dir, step_name="step_01")
"""
from __future__ import annotations

import json
from pathlib import Path
from typing import Any


def _action_to_code(action: dict[str, Any], index: int) -> str:
    """Convert a single resolved action dict to PyAutoGUI Python code."""
    action_type = action.get("action", "")
    lines = [f"    # Action {index}: {action_type}"]

    if action_type == "click":
        x = action.get("x", 0)
        y = action.get("y", 0)
        target = action.get("target", "")
        lines.append(f'    print("Clicking \'{target}\' at ({x}, {y})")')
        lines.append(f"    pyautogui.click({x}, {y}, duration=0.4)")
        lines.append(f"    time.sleep(1.0)")

    elif action_type == "type":
        x = action.get("x", 0)
        y = action.get("y", 0)
        value = action.get("value", "")
        field = action.get("field_target", "")
        field_found = action.get("_field_found", True)
        escaped_value = value.replace("\\", "\\\\").replace('"', '\\"')

        if field_found:
            lines.append(f'    print("Typing \\"{escaped_value}\\" into \\"{field}\\"")')
            lines.append(f"    pyautogui.click({x}, {y}, clicks=3, interval=0.1)")
            lines.append(f"    time.sleep(0.3)")
        else:
            lines.append(f'    print("Typing \\"{escaped_value}\\" into focused field")')

        lines.append(f'    subprocess.run(["pbcopy"], input="{escaped_value}".encode(), check=True)')
        lines.append(f"    pyautogui.hotkey('command', 'v')")
        lines.append(f"    time.sleep(1.0)")

    elif action_type == "scroll":
        x = action.get("x", 0)
        y = action.get("y", 0)
        clicks = action.get("clicks", -3)
        target = action.get("target", "")
        lines.append(f'    print("Scrolling at \'{target}\' ({x}, {y}) by {clicks}")')
        lines.append(f"    pyautogui.scroll({clicks}, x={x}, y={y})")
        lines.append(f"    time.sleep(1.0)")

    elif action_type == "shell":
        command = action.get("command", "")
        wait = action.get("wait", 1)
        escaped_cmd = command.replace("\\", "\\\\").replace('"', '\\"')
        lines.append(f'    print("Running: {escaped_cmd[:60]}")')
        lines.append(f'    subprocess.run("{escaped_cmd}", shell=True, check=True)')
        lines.append(f"    time.sleep({wait})")

    elif action_type == "hotkey":
        keys = action.get("keys", [])
        keys_repr = ", ".join(f'"{k}"' for k in keys)
        lines.append(f'    print("Hotkey: {"+".join(keys)}")')
        lines.append(f"    pyautogui.hotkey({keys_repr})")
        lines.append(f"    time.sleep(1.0)")

    return "\n".join(lines)


def generate_script(
    actions: list[dict[str, Any]],
    output_dir: Path,
    step_name: str = "replay",
) -> Path:
    """
    Generate a standalone PyAutoGUI script from resolved actions.

    Args:
        actions: List of resolved action dicts (with x/y coordinates).
        output_dir: Directory to write the script to.
        step_name: Name for the script file.

    Returns:
        Path to the generated .py file.
    """
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    action_blocks = []
    for i, action in enumerate(actions, 1):
        action_blocks.append(_action_to_code(action, i))

    script = f'''\
#!/usr/bin/env python3
"""
Auto-generated PyAutoGUI replay script: {step_name}
Generated by FlowCast codegen.

Run with:
    python {step_name}.py

Requires: pip install pyautogui
Note: Screen coordinates are hardcoded from the original recording.
"""
import subprocess
import time

import pyautogui

pyautogui.FAILSAFE = True
pyautogui.PAUSE = 0.3
pyautogui.MINIMUM_DURATION = 0.3


def main():
    print("Starting replay: {step_name}")
    print("Move mouse to top-left corner to abort (failsafe)")
    time.sleep(2)  # Grace period before starting

{chr(10).join(action_blocks)}

    print("Replay complete: {step_name}")


if __name__ == "__main__":
    main()
'''

    script_path = output_dir / f"{step_name}.py"
    script_path.write_text(script)
    print(f"[codegen] Script saved → {script_path}")
    return script_path


def generate_all_scripts(
    steps_actions: dict[str, list[dict[str, Any]]],
    output_dir: Path,
) -> list[Path]:
    """
    Generate replay scripts for all steps.

    Args:
        steps_actions: Dict mapping step names to their resolved actions.
        output_dir: Directory to write scripts to.

    Returns:
        List of generated script paths.
    """
    scripts = []
    for step_name, actions in steps_actions.items():
        path = generate_script(actions, output_dir, step_name)
        scripts.append(path)
    return scripts
