"""Which WSO2 Integrator docs pages can FlowCast follow, start to finish?

`tools/doc_to_workflow.py` converts ONE pasted page. This module reads the
whole docs source (https://github.com/wso2/docs-integrator, the Markdown the
site at https://wso2.com/integration-platform/docs/ is built from) and, for
every page, answers the question the recorder actually cares about: if FlowCast
were handed this page, would every instruction turn into an action it can run?

The answer is decided by the real parser, not by guessing. Each numbered
instruction is normalised (the docs say "click", the parser speaks "Select"),
passed through `doc_to_workflow.rewrite`, then through
`parser._parse_instructions`. A line either produces actions, is purely
informational ("Confirm the response shows 200 OK"), or is UNPARSED — and one
unparsed line means a person has to step in.

Verdicts, strictest first:

    ready    every line parses, nothing outside WSO2 Integrator is needed.
             This is the "100% followable" set.
    auto     every line parses once FlowCast starts the page's prerequisites
             itself (a broker or database container, kb/prereq_recipes.json)
             and sends its test event. Hands-free, with Docker.
    keys     every line parses, but the page's configurables need values only
             you have (an API key, a tenant URL). Enter them once in FlowCast
             Studio; they are written to Config.toml, never typed on camera.
    setup    every line parses, but the page needs something FlowCast cannot
             create or be given: an account to sign up for, a cloud console.
    partial  a walkthrough, but some lines have no concrete value or no rule
             ("configure the following fields") — needs a person.
    none     not a walkthrough: concepts, reference, overviews.

The parse is static. A `ready` page has a workflow FlowCast can execute line
for line; whether every click lands is only proven by recording it, which is
what the `verified` flag records.
"""
from __future__ import annotations

import json
import re
import subprocess
import sys
from dataclasses import asdict, dataclass, field
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from src import prereqs  # noqa: E402
from src.parser import _parse_instructions  # noqa: E402
from tools.doc_to_workflow import rewrite as _dtw_rewrite  # noqa: E402

DOCS_REPO = "https://github.com/wso2/docs-integrator.git"
DOCS_SITE = "https://wso2.com/integration-platform/docs"
SOURCE_DIR = ROOT / "output" / "docs-src" / "docs-integrator"
CATALOG = ROOT / "kb" / "docs_catalog.json"
WORKFLOW_DIR = ROOT / "kb" / "docs_workflows"

VERDICTS = ("ready", "auto", "keys", "setup", "partial", "none")

# First line of every generated workflow. A copy in workflows/ that still starts
# with it is refreshed when the docs or the generator change; delete the line
# to keep your own edits.
GENERATED_MARK = "<!-- generated by FlowCast Studio from"

# Recorded workflows whose doc page has been filmed end to end. The workflow
# slugs predate this catalog, so they are matched to doc pages by hand.
VERIFIED_WORKFLOWS = {
    "get-started/build-integration-api": "build-integration-api",
    "get-started/build-automation": "quick-start-automation",
    "get-started/build-ai-agent": "quick-start-ai-agent",
    "get-started/build-file-driven-integration": "quick-start-file",
    "get-started/build-event-driven-integration": "build-event-integration",
}


# ── source checkout ──────────────────────────────────────────────────────────

def sync_source(dest: Path = SOURCE_DIR) -> Path:
    """Fetch (or update) the docs Markdown only.

    The repo is mostly images; a blobless, sparse checkout of `*.md` brings
    the clone from minutes to seconds.
    """
    dest.parent.mkdir(parents=True, exist_ok=True)
    if not (dest / ".git").exists():
        subprocess.run(["git", "clone", "--depth", "1", "--filter=blob:none",
                        "--no-checkout", DOCS_REPO, str(dest)], check=True)
        subprocess.run(["git", "-C", str(dest), "sparse-checkout", "set", "--no-cone",
                        "/en/docs/**/*.md", "/en/docs/**/*.mdx"], check=True)
        subprocess.run(["git", "-C", str(dest), "checkout", "main"], check=True)
    else:
        subprocess.run(["git", "-C", str(dest), "pull", "--depth", "1", "--quiet"],
                       check=True)
    return dest / "en" / "docs"


def source_commit(dest: Path = SOURCE_DIR) -> str:
    r = subprocess.run(["git", "-C", str(dest), "log", "-1", "--format=%h %cs"],
                       capture_output=True, text=True)
    return r.stdout.strip()


# ── Markdown → procedure ─────────────────────────────────────────────────────

FRONTMATTER_RE = re.compile(r"\A---\n(.*?)\n---\n", re.S)
# Innermost first: an OS picker can sit inside the Visual Designer tab.
TABS_RE = re.compile(r"<Tabs\b[^>]*>((?:(?!<Tabs\b).)*?)</Tabs>", re.S)
TABITEM_RE = re.compile(r"<TabItem\b([^>]*)>(.*?)</TabItem>", re.S)
FENCE_RE = re.compile(r"^(\s*)```(\w*)[^\n]*\n(.*?)^\s*```\s*$", re.S | re.M)
ADMONITION_RE = re.compile(r"^:::(\w+)[^\n]*\n(.*?)^:::\s*$", re.S | re.M)
JSX_BLOCK_RE = re.compile(r"<([A-Z]\w*)\b[^>]*?/>|<([A-Z]\w*)\b.*?</\2>", re.S)
HEADING_RE = re.compile(r"^(#{1,4})\s+(.+?)\s*#*\s*$")
STEP_HEADING_RE = re.compile(r"^Step\s+(\d+)\s*[:.\-–—]?\s*(.*)$", re.I)
NUMBERED_RE = re.compile(r"^( {0,3})(\d+)[.)]\s+(.*\S)\s*$")
SUB_BULLET_RE = re.compile(r"^\s{2,}[-*+]\s+(.*\S)\s*$")
META_RE = re.compile(r"\*\*Time:\*\*\s*(?P<time>[^|]+?)\s*\|\s*\*\*What you'?ll build:\*\*\s*(?P<build>.+)")

IMPERATIVE = re.compile(
    r"^(?:in the [^,]+,\s*)?(select|click|choose|pick|set|enter|type|search|add|open|"
    r"run|press|go to|navigate|expand|drag|toggle|enable|disable|fill|provide|"
    r"configure|create|save|paste|replace|copy|upload|scroll|right-click|bind|hover|"
    r"locate|place|switch|leave|update|edit|define|write|send|invoke|test|deploy)\b", re.I)

INFORMATIONAL = re.compile(
    r"^\s*(keep|confirm|verify|check|ensure|observe|notice|note|review|wait for|"
    r"you (?:should|will|can) see|the\b|this\b|a\b|an\b|it\b|once\b|after\b|"
    r"when\b|wso2 integrator (?:opens|displays|shows|creates|generates|adds))", re.I)


@dataclass
class Line:
    source: str                 # the doc's own wording
    workflow: list[str]         # parser-legal line(s) it became; [] if none
    actions: int                # actions the real parser made of them
    kind: str                   # action | info | mixed | unparsed
    manual: str = ""            # the part a person does (mixed / unparsed)


@dataclass
class Step:
    n: int
    title: str
    lines: list[Line] = field(default_factory=list)


@dataclass
class Page:
    path: str                   # relative to en/docs, no extension
    url: str
    title: str
    description: str
    section: str
    area: str
    slug: str
    time: str = ""
    build: str = ""
    steps: list[Step] = field(default_factory=list)
    blockers: list[str] = field(default_factory=list)
    notes: list[str] = field(default_factory=list)
    verdict: str = "none"
    coverage: float = 0.0
    action_count: int = 0
    unparsed: list[str] = field(default_factory=list)
    requires: list[str] = field(default_factory=list)   # prerequisite items, verbatim
    setup_commands: list[str] = field(default_factory=list)  # run before step 1
    starts_in_project: bool = False                     # FlowCast creates one first
    recipes: list[str] = field(default_factory=list)    # prerequisites FlowCast starts
    inputs: list[dict] = field(default_factory=list)    # configurables needing values
    bindings: list[dict] = field(default_factory=list)  # connection field → configurable
    service: str | None = None                          # the outside service it talks to
    manual_requires: list[str] = field(default_factory=list)  # neither started nor keyable
    project: str | None = None                          # WSO2 project name it creates
    notes_extra: list[str] = field(default_factory=list)  # e.g. an optional step left out
    verified: str | None = None
    workflow_file: str | None = None


def _frontmatter(raw: str) -> tuple[dict, str]:
    m = FRONTMATTER_RE.match(raw)
    if not m:
        return {}, raw
    fm = {}
    for ln in m.group(1).splitlines():
        k, sep, v = ln.partition(":")
        if sep and not ln.startswith(" "):
            fm[k.strip()] = v.strip().strip('"').strip("'")
    return fm, raw[m.end():]


def _pick_tab(block: str) -> str:
    """Keep the Visual Designer tab — the one FlowCast can click through.

    Pages offer the same build as UI steps and as Ballerina code; the code tab
    is useless to a screen recorder. Failing a UI tab, take the default one.
    """
    items = TABITEM_RE.findall(block)
    if not items:
        return block
    for attrs, body in items:
        if re.search(r'value="(?:ui|unix|mac|macos)"|label="[^"]*(visual|designer|low-code|'
                     r'\bui\b|macos)', attrs, re.I):
            return body
    for attrs, body in items:
        if "default" in attrs:
            return body
    return items[0][1]


FENCE_MARK = "\u27e6FENCE:{}\u27e7"
FENCE_MARK_RE = re.compile(r"\u27e6FENCE:(\d+)\u27e7")
SHELL_LANGS = ("bash", "sh", "shell", "zsh", "console")


def _clean(body: str) -> tuple[str, list[tuple[str, str]], list[str], str]:
    """Return (procedure text, code fences, admonition texts, prerequisites).

    Each code fence leaves a marker in the text so the instruction it belongs
    to ("Run the modify command in your terminal:") can find it again.
    """
    while TABS_RE.search(body):
        body = TABS_RE.sub(lambda m: _pick_tab(m.group(1)), body)
    body = re.sub(r"^import .*$", "", body, flags=re.M)
    fences: list[tuple[str, str]] = []

    def _mark(m: re.Match) -> str:
        fences.append((m.group(2).lower(), m.group(3)))
        return f"{m.group(1)}{FENCE_MARK.format(len(fences) - 1)}"
    body = FENCE_RE.sub(_mark, body)
    admonitions, prereq = [], []
    for m in ADMONITION_RE.finditer(body):
        head = body[m.start():body.index("\n", m.start())]
        (prereq if re.search(r"prerequisite|before you begin", head, re.I)
         else admonitions).append(m.group(2))
    body = ADMONITION_RE.sub("", body)
    for m in re.finditer(r"^#{2,3}\s+(?:Prerequisites?|Before you begin|Requirements)\s*\n"
                         r"(.*?)(?=^#{1,3}\s|\Z)", body, re.S | re.M | re.I):
        prereq.append(m.group(1))
    body = JSX_BLOCK_RE.sub("", body)
    body = re.sub(r"!\[[^\]]*\]\([^)]*\)", "", body)           # images
    # `<username>@<companyID>` is a placeholder, not markup: keep it readable.
    body = re.sub(r"`[^`\n]*`", lambda m: m.group(0).replace("<", "‹").replace(">", "›"), body)
    body = re.sub(r"<[^>\n]+>", "", body)                      # stray html
    return body, fences, admonitions, "\n".join(prereq)


# Prerequisite bullets that only ask for WSO2 Integrator itself.
OWN_ENVIRONMENT = re.compile(
    r"WSO2 Integrator|cloud setup|local setup|cloud editor|VS ?Code|Visual Studio Code|"
    r"working .*environment|Ballerina|basic (?:knowledge|understanding|familiarity)|"
    r"familiar(?:ity)? with|completed? the|understanding of", re.I)


def _requirements(prereq: str, fences: list[tuple[str, str]]) -> tuple[list[str], list[str]]:
    """(what a page needs that FlowCast cannot set up, commands it can run to
    set the rest up itself).

    Every prerequisite bullet counts except the ones asking for WSO2 Integrator
    itself — and except a bullet that carries its own one-line local command
    ("A file at the listener path. Create one: touch /tmp/x"), which FlowCast
    runs before step 1 instead.
    """
    out: list[str] = []
    setup: list[str] = []
    bullets: list[list[str]] = []
    for ln in prereq.splitlines():
        if re.match(r"^\s*[-*]\s+\S", ln):
            bullets.append([ln])
        elif bullets:
            bullets[-1].append(ln)
    for chunk in bullets:
        first = re.sub(r"^\s*[-*]\s+", "", chunk[0])
        item = re.sub(r"\[([^\]]+)\]\([^)]*\)", r"\1", first)
        item = FENCE_MARK_RE.sub("", re.sub(r"[*`]", "", item)).strip(" :")
        if not item or OWN_ENVIRONMENT.search(item) or len(item) <= 3:
            continue
        cmds = [c for c in (_shell_command(fences[int(m.group(1))])
                            for m in FENCE_MARK_RE.finditer("\n".join(chunk))) if c]
        if cmds:
            setup.append(cmds[0])
        else:
            out.append(item[:140])
    if not out and not setup and not bullets:
        # Prose prerequisites ("CDC must be enabled on the SQL Server database")
        prose = re.sub(r"\s+", " ", FENCE_MARK_RE.sub("", prereq)).strip()
        if prose and not OWN_ENVIRONMENT.search(prose):
            out.append(prose[:140])
    return out, setup


def _sections(body: str) -> list[tuple[int, str, list[str]]]:
    out: list[tuple[int, str, list[str]]] = [(1, "", [])]
    for ln in body.splitlines():
        m = HEADING_RE.match(ln)
        if m:
            out.append((len(m.group(1)), m.group(2).strip(), []))
        else:
            out[-1][2].append(ln)
    return out


def _items(lines: list[str]) -> list[str]:
    """Numbered instructions, each with its indented sub-bullets folded in as
    separate entries (they are usually 'set field X to Y' details)."""
    items: list[str] = []
    for ln in lines:
        m = NUMBERED_RE.match(ln)
        if m:
            items.append(m.group(3))
            continue
        if items and FENCE_MARK_RE.search(ln):
            items[-1] += " " + FENCE_MARK_RE.search(ln).group(0)
            continue
        m = SUB_BULLET_RE.match(ln)
        if m and items:
            items.append("  - " + m.group(1))
            continue
        if items and ln.startswith("   ") and ln.strip() and not ln.strip().startswith("|"):
            # wrapped continuation of the previous numbered line
            if not items[-1].startswith("  - "):
                items[-1] += " " + ln.strip()
    return items


def _paragraph_items(lines: list[str]) -> list[str]:
    """A Step section written as prose ('Click **Save Connection**. The node
    appears.') — keep the imperative sentences."""
    text = " ".join(ln.strip() for ln in lines if ln.strip() and not ln.strip().startswith("|"))
    sentences = re.split(r"(?<=[.!])\s+(?=[A-Z*])", text)
    return [s for s in sentences if IMPERATIVE.match(s)]


# ── one instruction → parser-legal lines ─────────────────────────────────────

CLICK_VERBS = re.compile(r"^(?P<pre>(?:in|on|from) the [^,]+,\s*)?(?:click|choose|pick|tap)\s+(?:on\s+)?", re.I)
ENTER_IN_RE = re.compile(
    r"^(?:enter|type|input)\s+`([^`]+)`\s+(?:in|into|as|for)\s+(?:the\s+)?\*\*([^*]+)\*\*(?:\s+(?:field|box|input))?\.?$", re.I)
SEARCH_TYPE_RE = re.compile(
    r"^(?:in the [^,]*search[^,]*,\s*)?(?:type|enter|search for|search)\s+`([^`]+)`(?:\s+in the search[\w ]*)?\.?$", re.I)
COMPOUND_SET_RE = re.compile(r"\s+and\s+(?=\*\*[^*]+\*\*\s+to\s+`)", re.I)
FIELD_VALUE_RE = re.compile(r"^\*\*([^*]+)\*\*\s*[:—–-]\s*`([^`]+)`\.?$")


# One-line commands FlowCast may run itself through the parser's shell action
# ("Run the shell command `X`"). Anything that installs, deploys, needs a
# placeholder filled in or reaches beyond this machine stays a blocker.
LOCAL_COMMAND = re.compile(r"^(echo|printf|touch|cat|cp|mv|mkdir|ls|curl)\b")
UNSAFE_COMMAND = re.compile(r"docker|kubectl|helm|sudo|brew|apt|pip|npm|git |ssh|bal |"
                            r"<[^>]+>|YOUR_|your-|\$\{|rm -rf|https://(?!localhost)", re.I)


def _shell_command(fence: tuple[str, str]) -> str | None:
    lang, code = fence
    lines = [ln.strip() for ln in code.splitlines()
             if ln.strip() and not ln.strip().startswith("#")]
    if lang not in SHELL_LANGS + ("",) or len(lines) != 1:
        return None
    cmd = lines[0].lstrip("$ ").strip()
    if not LOCAL_COMMAND.match(cmd) or UNSAFE_COMMAND.search(cmd) or "`" in cmd:
        return None
    if cmd.startswith("curl") and not re.search(r"localhost|127\.0\.0\.1", cmd):
        return None
    return cmd


def _normalise(text: str, fences: list[tuple[str, str]] | None = None) -> list[str]:
    """The docs' phrasing → the phrasings the parser and doc_to_workflow know.

    Returns zero or more candidate lines. Never invents a value: a field whose
    value is described ("your database username") stays unparsed.
    """
    fm = FENCE_MARK_RE.search(text)
    if fm:
        text = FENCE_MARK_RE.sub("", text).strip()
        cmd = _shell_command(fences[int(fm.group(1))]) if fences else None
        if cmd and re.search(r"\b(run|execute|send|trigger|create|publish|terminal|command)\b",
                             text, re.I):
            return [f"Run the shell command `{cmd}`."]
    t = re.sub(r"\[([^\]]+)\]\([^)]*\)", r"\1", text).strip()     # links → text
    t = re.sub(r"\s+\(see [^)]*\)", "", t)
    t = t.replace("\\", "")
    # "`/tmp` (macOS/Linux) or `C:\tmp` (Windows)" — this records on a Mac.
    t = re.sub(r"\s*\((?:macOS(?:/Linux)?|Linux/macOS)\)\s*or\s*`[^`]*`\s*\(Windows\)", "", t)

    sub = t.startswith("  - ")
    if sub:
        t = t[4:].strip()
        m = FIELD_VALUE_RE.match(t)
        if m:
            return [f"Set **{m.group(1)}** to `{m.group(2)}`."]
        return [t]

    if re.match(r"^\*\*[^*]+\*\*\.?$", t):                       # "**Create Integration**."
        return [f"Select {t.rstrip('.')}."]

    # Expanding a tree node is a click on it: "Expand **Connections → client**",
    # "Under **Connections**, expand **client** to view its operations".
    m = re.match(r"^(?:under \*\*([^*]+)\*\*,\s*)?(?:click to )?expand(?: the)? \*\*([^*]+)\*\*", t, re.I)
    if m:
        scope, node = m.group(1), m.group(2)
        parts = [x.strip() for x in re.split(r"\s*(?:→|->|>)\s*", node) if x.strip()]
        if len(parts) > 1:
            scope, node = parts[-2], parts[-1]
        return [f"Select **{node}** under **{scope}**." if scope else f"Select **{node}**."]

    m = CLICK_VERBS.match(t)
    if m:
        t = (m.group("pre") or "") + ("select " if m.group("pre") else "Select ") + t[m.end():]

    m = ENTER_IN_RE.match(t)
    if m:
        return [f"Set **{m.group(2)}** to `{m.group(1)}`."]

    m = SEARCH_TYPE_RE.match(t)
    if m:
        return [f"Search for `{m.group(1)}`."]

    # "Set **Host** to `localhost` and **Port** to `5672` (…)" → two lines.
    if re.match(r"^set\b", t, re.I) and COMPOUND_SET_RE.search(t):
        parts = COMPOUND_SET_RE.split(t)
        out = [parts[0].rstrip(".") + "."]
        for p in parts[1:]:
            p = re.sub(r"\s*\([^)]*\)\s*\.?$", "", p).rstrip(".")
            out.append(f"Set {p}.")
        return out

    t = re.sub(r"\s*\((?:update|change|optional|if )[^)]*\)", "", t)
    return [t]


def _parse(line: str) -> int:
    return len(_parse_instructions(f"1. {line}"))


# An instruction that tells the reader to decide something. It may still
# contain a clickable word ("Fill in the form fields and select Create"), but
# following it to the letter needs values the page never gives.
VAGUE = re.compile(
    r"\b(fill in|fill out|configure the (?:following|fields|settings|required)|"
    r"(?:enter|set|provide|specify) (?:a|an|your|the required|the following|any)\b(?! `)|"
    r"give (?:it|the \w+) a\b|add (?:its|the|your) (?:fields|values|details|logic)|"
    r"write (?:the|your)|implement (?:the|your)|define the (?:input|output|logic)|"
    r"as needed|if needed|your own|as required)", re.I)
ACTION_WORD = re.compile(r"\b(select|click|set|search|add|press)\s+\*\*", re.I)


def _grounded(source: str, line: str, integration: str | None) -> bool:
    """Every target the parser took from `line` is something the doc itself
    marked as a UI label (bold) or a value (code) — not a phrase the rewrite
    wrapped in bold on its own initiative."""
    marked = {m.lower().strip() for m in re.findall(r"\*\*([^*]+)\*\*|`([^`]+)`", source)
              for m in m if m}
    marked |= {part.strip() for m in list(marked) for part in re.split(r"→|->|>", m)}
    if integration:
        marked.add(integration.lower())
    marked.add("skip for now")
    for act in _parse_instructions(f"1. {line}"):
        kind = act["action"]
        want = act.get("target") if kind == "click" else act.get("value") \
            if kind in ("type", "search", "select") else None
        if want and want.lower().strip() not in marked and not (
                kind == "click" and want.lower() in source.lower() and
                re.search(r"\*\*" + re.escape(want), source, re.I)):
            return False
    return True


# Verbs FlowCast has no action for. A clause starting with one is left to a
# person even when the rest of its sentence parses ("select the card, and bind
# each connection parameter to a configurable variable").
NO_ACTION_VERB = re.compile(
    r"^(?:then\s+|and\s+)*(bind|hover|configure|fill|provide|define|write|locate|place|"
    r"switch|update|edit|drag|right-click|copy|paste|replace|upload|enter|type|set|give|"
    r"add (?:its|the|your|a|an) (?!\*\*)|choose (?:a|an|your)|pick (?:a|an|your)|review)\b", re.I)
CLAUSE_SPLIT = re.compile(r";\s*|\.\s+(?=[A-Z*])|,\s*(?:and\s+|then\s+)?(?=(?:then\s+)?[a-z]+\b)|"
                          r"\s+(?:and|then)\s+(?=(?:then\s+)?(?:select|click|bind|hover|set|enter|"
                          r"search|expand|configure|fill|type|choose|open|add)\b)", re.I)


def _uncovered(text: str, integration: str | None) -> list[str]:
    """Clauses of an instruction that ask for something no parsed action does."""
    out = []
    body = re.split(r":\s*(?=-\s|\s*$)", text)[0]          # the list after "…fields:" is detail
    for clause in CLAUSE_SPLIT.split(body):
        c = clause.strip(" .")
        plain = re.sub(r"[*`]", "", c)
        if not plain or not NO_ACTION_VERB.match(plain):
            continue
        cands = _normalise(c)
        if any(_parse(x) or _parse(_dtw_rewrite(x, integration)[0]) for x in cands) \
                and not re.match(r"^(?:then\s+|and\s+)*(bind|hover|configure|fill|provide)\b", plain, re.I):
            continue
        out.append(plain)
    return out


def _clauses(line: str, integration: str | None, source: str) -> list[str]:
    """The line's imperative clauses as parser-legal lines, or [] if it has one."""
    parts = [c.strip(" .") for c in re.split(r",\s*(?:and\s+|then\s+)|\s+(?:and|then)\s+(?=(?:select|click|"
                                             r"search|set|enter|type|press|add)\b)|;\s*", line, flags=re.I)]
    parts = [p for p in parts if p]
    if len(parts) < 2:
        return []
    out = []
    for part in parts:
        cand = next((c for c in _normalise(part[0].upper() + part[1:]) if _parse(c)), None)
        if cand is None:
            rewritten = _dtw_rewrite(part[0].upper() + part[1:], integration)[0]
            cand = rewritten if _parse(rewritten) else None
        if cand is not None and _grounded(source, cand, integration):
            out.append(cand.rstrip(".") + ".")
    return out


def convert_line(text: str, integration: str | None,
                 fences: list[tuple[str, str]] | None = None) -> Line:
    text = text if fences is not None else FENCE_MARK_RE.sub("", text)
    candidates = _normalise(text, fences)
    text = FENCE_MARK_RE.sub("", text).strip()
    plain = re.sub(r"[*`]", "", text).strip().lstrip("- ")
    if INFORMATIONAL.match(plain) and not IMPERATIVE.match(plain) \
            and not ACTION_WORD.search(text):
        return Line(text, [], 0, "info")
    out: list[str] = []
    total = 0
    for cand in candidates:
        n = _parse(cand)
        line = cand
        if n == 0:
            rewritten, _note = _dtw_rewrite(cand, integration)
            if _parse(rewritten):
                line, n = rewritten, _parse(rewritten)
        if n and (line.startswith("Run the shell command") or _grounded(text, line, integration)):
            # The parser takes the first rule that matches a line, so a compound
            # instruction can lose a clause: "Search for `printInfo` and select
            # **printInfo**" parses to the click alone, and the search is never
            # typed. When its clauses, parsed one by one, do more than the whole
            # line did, use the clauses.
            split = _clauses(cand, integration, text)
            if split and sum(_parse(c) for c in split) > n:
                out += split
                total += sum(_parse(c) for c in split)
                continue
            out.append(line)
            total += n
    if total and VAGUE.search(plain) and not any(re.match(r"Set \*\*", w) for w in out):
        return Line(text, out, total, "mixed", manual=plain)
    if total and not any(w.startswith("Run the shell command") for w in out):
        left = _uncovered(text, integration)
        if left:
            return Line(text, out, total, "mixed", manual="; ".join(left))
    if total:
        return Line(text, out, total, "action")
    if INFORMATIONAL.match(plain) and not IMPERATIVE.match(plain):
        return Line(text, [], 0, "info")
    return Line(text, [], 0, "unparsed")


# ── blockers: what FlowCast cannot create on its own ─────────────────────────

BLOCKERS: list[tuple[str, re.Pattern]] = [
    ("credentials", re.compile(
        r"\b(api[ -]?key|access[ -]token|auth(?:entication)? token|client (?:id|secret)|"
        r"secret key|consumer (?:key|secret)|bearer token|oauth|refresh token|"
        r"account sid|app password|service account|private key|keystore|"
        r"personal access token|webhook secret)\b", re.I)),
    ("account", re.compile(
        r"\b(sign up|create an? (?:free )?account|developer (?:portal|console|account)|"
        r"(?:aws|azure|google cloud|gcp) (?:account|console|portal)|"
        r"(?:salesforce|slack|github|twilio|stripe|hubspot|zoom|shopify|jira|sap) "
        r"(?:account|org|organization|workspace|instance))\b", re.I)),
    ("service", re.compile(
        r"\b(a running [\w ]{0,40}(?:instance|server|broker|database|cluster)|"
        r"docker run|docker compose|running (?:mysql|postgres\w*|kafka|rabbitmq|redis|"
        r"mongodb|mssql|oracle|solace|mqtt)|(?:mysql|postgresql|mssql|oracle|mongodb|redis|"
        r"kafka|rabbitmq|mqtt|solace|activemq|ftp|sftp|smtp|imap|pop3) (?:server|broker|"
        r"instance|database|cluster))\b", re.I)),
    ("terminal", re.compile(r"\b(bal (?:new|run|build|test|persist|openapi|grpc|graphql|"
                            r"pack|push|add)|curl\s|kubectl|helm |terminal window|"
                            r"command line|in a terminal|open a terminal)\b", re.I)),
    ("code", re.compile(r"\b(add the following (?:code|ballerina)|paste the following|"
                        r"replace the (?:generated )?code|in the code editor|"
                        r"switch to (?:the )?(?:code|source) view|edit the \S+\.bal)\b", re.I)),
    ("external-ui", re.compile(r"\b(management ui|postman|open (?:a |your )?browser|"
                               r"web browser|\bgo to https?://)", re.I)),
]
SOFT = {
    "wso2-sign-in": re.compile(r"\b(WSO2 (?:Integrator )?Copilot|WSO2 model provider|"
                               r"sign in to WSO2|WSO2 account)\b", re.I),
}


def _blockers(text: str, open_fences: list[tuple[str, str]],
              requires: list[str]) -> tuple[list[str], list[str]]:
    """`text` is the chosen (Visual Designer) tab plus its admonitions — the
    Ballerina Code tab is gone by now, so its code does not count against a
    page whose UI steps never ask for any. `open_fences` are the shell blocks
    FlowCast could NOT turn into its own shell action."""
    soft = [name for name, rx in SOFT.items() if rx.search(text)]
    # A sentence about signing in to WSO2 Copilot mentions an "access token";
    # that is the soft one-time sign-in, not a credential to go and create.
    scrubbed = " ".join(s for s in re.split(r"(?<=[.!?])\s+|\n", text)
                        if not any(rx.search(s) for rx in SOFT.values()))
    hard = [name for name, rx in BLOCKERS if rx.search(scrubbed)]
    if any(lang in SHELL_LANGS + ("cmd", "powershell") for lang, _ in open_fences) \
            and "terminal" not in hard:
        hard.append("terminal")
    if requires:
        hard.append("prerequisite")
    return hard, soft


# ── configurables, prerequisites, test events ────────────────────────────────

VALUES_LINE = re.compile(r"(?:set|enter|provide|specify) (?:a |the )?values? for (?:each|all|the|your)\b.*"
                         r"configurables?|set actual values|values (?:for|of) (?:your|the|each) configurables?",
                         re.I)
CONFIG_BULLET = re.compile(r"^\s*[-*]\s+\*\*([A-Za-z_]\w*)\*\*\s*(.*)$")
TYPE_IN_PARENS = re.compile(r"\(\s*`?(?:configurable\s+)?((?:string|int|boolean|decimal|float|byte|json|"
                            r"map<[^>]+>)(?:\[\])?\??)`?\s*\)")
TYPE_LEADING = re.compile(r"^[:—–-]?\s*((?:string|int|boolean|decimal|float)(?:\[\])?\??)\s*[:—–-]\s*")
SECRET_NAME = re.compile(r"key|token|secret|pass(?:word)?|pwd|sid|credential|private", re.I)


def _input(name: str, rest: str) -> dict:
    typ = "string"
    m = TYPE_IN_PARENS.search(rest)
    if m:
        typ, rest = m.group(1), rest.replace(m.group(0), "")
    else:
        m = TYPE_LEADING.match(rest)
        if m:
            typ, rest = m.group(1), rest[m.end():]
    m = re.search(r"of type `([\w\[\]?]+)`", rest)
    if m:
        typ = m.group(1)
    ex = re.search(r"(?:e\.g\.|for example)[,:]?\s*`([^`]+)`(?! of type)", rest)
    desc = re.sub(r"\s+", " ", re.sub(r"[*`]", "", rest)).strip(" :—–-.")
    return {"name": name, "type": typ.rstrip("?"), "label": desc[:160] or name,
            "secret": bool(SECRET_NAME.search(name) or re.search(r"\b(token|secret|password|api key)\b",
                                                                   desc, re.I)),
            "example": ex.group(1) if ex else None, "auto": None}


BIND_VAR = [
    re.compile(r"bound to (?:the |a |an )?(?:new )?`(\w+)`", re.I),
    re.compile(r"bind(?:ed)?(?: it)? to (?:the |a |an )?(?:new )?`(\w+)`", re.I),
    re.compile(r"\((?:e\.g\.|for example),? `(\w+)` of type `([\w\[\]?]+)`", re.I),
    re.compile(r"`(\w+)` configurable", re.I),
]
# "bind `username` to a `sfUsername` configurable variable and `password` to a
# `sfPassword` configurable variable" — the second pair has no "bind" of its own.
BIND_NESTED = re.compile(r"`(\w+)` to (?:the |a |an )?(?:new )?`(\w+)`", re.I)


def _bindings(text: str, inputs: list[dict]) -> list[dict]:
    """The connection fields a page binds to configurable variables.

    The docs phrase it every which way — "bound to the `x` configurable
    variable", "(e.g., `jdbcUrl` of type `string`)", "bind `username` to a
    `sfUsername` configurable" for a field inside a record — so several
    patterns are tried per bullet. A bullet that names no variable gets the
    input it most resembles, or none (FlowCast then asks)."""
    lines = text.splitlines()
    out, seen = [], set()
    types = {i["name"]: i["type"] for i in inputs}
    for i, ln in enumerate(lines):
        if not re.search(r"\b(bind|bound|binding)\b", ln, re.I) or not re.search(r"configurable", ln, re.I):
            continue
        if CONFIG_BULLET.match(ln) is None and VALUES_LINE.search(ln):
            continue
        for nxt in [ln] + lines[i + 1:i + 30]:
            m = re.match(r"^\s*[-*]\s+\*\*([^*]+)\*\*\s*(.*)$", nxt)
            if not m:
                if nxt is ln or not nxt.strip() or re.match(r"^\s{3,}\S", nxt):
                    continue
                break
            fieldname, rest = m.group(1).strip(), m.group(2)
            nested = BIND_NESTED.findall(rest) if re.search(r"\bbind\b", rest, re.I) else []
            if nested:
                for sub, var in nested:
                    key = f"{fieldname}.{sub}"
                    if key not in seen:
                        seen.add(key)
                        out.append({"field": fieldname, "sub": sub, "variable": var,
                                    "type": types.get(var, "string"), "nested": True})
                continue
            var, typ = None, None
            for rx in BIND_VAR:
                mm = rx.search(rest)
                if mm:
                    var = mm.group(1)
                    typ = mm.group(2) if mm.lastindex and mm.lastindex > 1 else None
                    break
            if var is None and re.search(r"\b(bind|bound)\b", rest + ln, re.I):
                want = norm_name(fieldname)
                var = next((i["name"] for i in inputs if norm_name(i["name"]).endswith(want)), None)
            if var and fieldname not in seen and not re.search(r"leave (?:as|it|empty|the default)", rest, re.I):
                seen.add(fieldname)
                out.append({"field": fieldname, "sub": None, "variable": var,
                            "type": typ or types.get(var, "string"), "nested": False})
    return out


def norm_name(s: str) -> str:
    return re.sub(r"[^a-z0-9]", "", s.lower())


# Connector folder → the service a person needs an account with. Folders not
# listed are named from their first segment ("hubspot.crm.lists" → HubSpot).
SERVICE_NAMES = {"microsoft": "Microsoft (Dynamics 365 / Entra ID)", "sap": "SAP", "hubspot": "HubSpot",
                 "googleapis": "Google", "aws": "AWS", "azure": "Azure", "asb": "Azure Service Bus",
                 "openai": "OpenAI", "salesforce": "Salesforce", "github": "GitHub", "slack": "Slack",
                 "zoom": "Zoom", "paypal": "PayPal", "mailchimp": "Mailchimp", "confluent": "Confluent Cloud",
                 "discord": "Discord", "twilio": "Twilio", "stripe": "Stripe", "mistral": "Mistral AI",
                 "elastic": "Elastic Cloud", "intercom": "Intercom", "gcloud": "Google Cloud",
                 "alfresco": "Alfresco", "ibm": "IBM", "milvus": "Milvus", "oracledb": "Oracle Database",
                 "nats": "NATS", "solace": "Solace", "jira": "Jira", "shopify": "Shopify",
                 "guidewire": "Guidewire", "anthropic": "Anthropic",
                 "java": "a JDBC database (runs locally)"}


def _service(rel: Path) -> str | None:
    p = rel.parts
    if len(p) > 3 and p[0] == "connectors" and p[1] == "catalog":
        key = p[3].split(".")[0].lower()
        return SERVICE_NAMES.get(key, key.replace("-", " ").title())
    return None


def _inputs(text: str) -> list[dict]:
    """Configurables a page asks values for, from the bullet list under its
    "Set a value for each configurable" line (or, failing that, under the
    "bind each field to a configurable" line)."""
    lines = text.splitlines()
    values: list[dict] = []
    binds: list[dict] = []
    for i, ln in enumerate(lines):
        if not re.search(r"configurable", ln, re.I) or CONFIG_BULLET.match(ln):
            continue
        target = values if VALUES_LINE.search(re.sub(r"[*`]", "", ln)) else binds
        for nxt in lines[i + 1:i + 40]:
            if not nxt.strip() or re.match(r"^\s{3,}\S", nxt) and not CONFIG_BULLET.match(nxt):
                continue
            m = CONFIG_BULLET.match(nxt)
            if not m:
                break
            name, rest = m.group(1), m.group(2)
            alias = re.search(r"`(\w+)` of type", rest)       # bind lists name the variable
            target.append(_input(alias.group(1) if alias else name, rest))
    chosen = values or binds
    seen, out = set(), []
    for inp in chosen:
        if inp["name"] not in seen:
            seen.add(inp["name"])
            out.append(inp)
    return out


def _recipes_for(requires: list[str]) -> list[str]:
    """One prerequisite recipe per requirement — the service it names first
    ("MySQL, PostgreSQL, MSSQL, or similar" is a MySQL page)."""
    ids: list[str] = []
    for item in requires:
        hits = [(m.start(), r["id"]) for r in prereqs.recipes()
                for m in [re.search(r["match"], item, re.I)] if m]
        if hits:
            rid = min(hits)[1]
            if rid not in ids:
                ids.append(rid)
    return ids


# A requirement the person running FlowCast satisfies by entering values:
# they have the account, the server, the key — FlowCast just needs to be told.
KEYABLE = re.compile(r"key|token|secret|credential|password|username|user id|connection details|"
                     r"account|subscription|tenant|client id|app registration|access to|url|endpoint|"
                     r"host|organi[sz]ation|workspace|instance|server|project id|region", re.I)


def _trigger(text: str, recipe_ids: list[str], names: dict[str, str]) -> str | None:
    """A doc line that sends the test event by hand → the recipe's command."""
    plain = re.sub(r"[*`]", "", text)
    for rid in recipe_ids:
        trig = prereqs.by_id(rid).get("trigger")
        if not trig or not re.search(trig["when"], plain, re.I):
            continue
        vals = {"queue": names.get("queue", "flowcast"), "topic": names.get("topic", "flowcast"),
                "payload": "hello-from-flowcast"}
        cmd, why = trig["command"].format(**vals), trig["why"].format(**vals)
        return f"Run the shell command `{cmd}` to {why}."
    return None


EPILOGUE = re.compile(r"^(?:deploy\b|deploy(?:ing)? to|next steps?|what'?s next|clean ?up|"
                      r"tear ?down|further reading)", re.I)


# ── page assembly ─────────────────────────────────────────────────────────────

def _url(rel: Path, fm: dict) -> str:
    if fm.get("slug"):
        return DOCS_SITE + "/" + fm["slug"].strip("/")
    parts = list(rel.with_suffix("").parts)
    if parts and parts[-1] == "index":
        parts = parts[:-1]
    return DOCS_SITE + "/" + "/".join(parts)


GENERIC_STEMS = {"example", "overview", "setup-guide", "actions", "action-reference",
                 "triggers", "trigger-reference", "connector-overview", "index"}


def _slug(rel: Path) -> str:
    parts = [p for p in rel.with_suffix("").parts]
    keep = parts[-1:]
    i = len(parts) - 1
    while keep[0] in GENERIC_STEMS and i > 0 or (len(keep) == 1 and re.match(r"^\d", keep[0])):
        i -= 1
        keep.insert(0, parts[i])
    return re.sub(r"[^a-z0-9]+", "-", "-".join(keep).lower()).strip("-")


def _area(rel: Path) -> str:
    p = rel.parts
    if p[0] == "connectors" and len(p) > 2 and p[1] == "catalog":
        return f"Connectors · {p[2].replace('-', ' ').title()}"
    names = {"get-started": "Get started", "develop": "Develop", "genai": "GenAI",
             "guides": "Guides", "connectors": "Connectors", "deploy": "Deploy",
             "deploy-operate": "Deploy & operate", "manage": "Manage",
             "reference": "Reference"}
    return names.get(p[0], p[0].title())


def analyse(path: Path, docs_root: Path) -> Page:
    rel = path.relative_to(docs_root)
    raw = path.read_text(errors="replace")
    fm, body = _frontmatter(raw)
    h1 = re.search(r"^#\s+(.+)$", body, re.M)
    title = fm.get("title") or (h1.group(1).strip() if h1 else rel.stem.replace("-", " ").title())
    page = Page(path=str(rel.with_suffix("")), url=_url(rel, fm), title=title,
                description=fm.get("description", ""), section="/".join(rel.parts[:2]),
                area=_area(rel), slug=_slug(rel))
    m = META_RE.search(body)
    if m:
        page.time, page.build = m.group("time").strip(), re.sub(r"[`*]", "", m.group("build")).strip()

    text, fences, admonitions, prereq = _clean(body)
    page.requires, page.setup_commands = _requirements(prereq, fences)
    sections = _sections(text)

    step_secs = [(lvl, STEP_HEADING_RE.match(h), ls) for lvl, h, ls in sections
                 if STEP_HEADING_RE.match(h)]
    raw_steps: list[tuple[str, list[str]]] = []
    if step_secs:
        for _lvl, m, ls in step_secs:
            items = _items(ls) or _paragraph_items(ls)
            if not items:
                # A step whose instruction is prose the rules above do not pick
                # up ("Bind every required connection field to a configurable
                # variable.") is still a step. Dropping it would make the page
                # look followable while the recording skips the hard part.
                prose = " ".join(ln.strip() for ln in ls if ln.strip()
                                 and not FENCE_MARK_RE.search(ln) and not ln.strip().startswith("|"))
                first = re.split(r"(?<=[.!:])\s+", prose)[0] if prose else ""
                if first and not INFORMATIONAL.match(re.sub(r"[*`]", "", first)):
                    items = [first]
            raw_steps.append((m.group(2).strip() or f"Step {m.group(1)}", items))
    else:
        # No "Step N" headings: a section with a numbered list of at least two
        # imperative lines is a procedure step of its own.
        for _lvl, h, ls in sections:
            items = _items(ls)
            if sum(1 for i in items if IMPERATIVE.match(re.sub(r"[*`]", "", i))) >= 2:
                raw_steps.append((h or page.title, items))

    integration = None
    names: dict[str, str] = {}
    for _t, items in raw_steps:
        for it in items:
            mm = re.search(r"Set\s+\*{0,2}Integration Name\*{0,2}\s+to\s+`([^`]+)`", it, re.I)
            if mm:
                integration = mm.group(1)
            mm = re.search(r"Set\s+\*{0,2}Project Name\*{0,2}\s+to\s+`([^`]+)`", it, re.I)
            if mm:
                page.project = mm.group(1)
            for key, rx in (("queue", r"Queue(?: Name)?"), ("topic", r"Topics?(?: Name)?")):
                mm = re.search(rf"\*\*{rx}\*\*\s+to\s+`([^`]+)`", it, re.I)
                if mm:
                    names[key] = mm.group(1)
    page.project = page.project or page.slug[:40]
    page.recipes = _recipes_for(page.requires)
    page.inputs = _inputs(text)
    page.bindings = _bindings(text, page.inputs)
    page.service = _service(rel)
    for inp in page.inputs:
        inp["auto"] = prereqs.value_for(inp["name"], page.recipes) if page.recipes else None

    triggered = False
    for n, (title_, items) in enumerate(raw_steps, 1):
        step = Step(n, re.sub(r"[`*]", "", title_))
        consume = False             # sub-bullets of a line replaced as a whole
        for it in items:
            if consume and it.startswith("  - "):
                step.lines.append(Line(FENCE_MARK_RE.sub("", it), [], 0, "info"))
                continue
            consume = False
            plain = re.sub(r"[*`]", "", it)
            if page.inputs and VALUES_LINE.search(plain):
                # Values go to Config.toml off camera; nothing secret is typed.
                expect = ",".join(i["name"] for i in page.inputs)
                cmd = (f".venv/bin/python tools/write_config.py --project {page.project} "
                       f"--expect {expect}")
                step.lines.append(Line(it, [f"Run the shell command `{cmd}` to set the "
                                            f"configurable values."], 1, "action"))
                consume = True
                continue
            line = convert_line(it, integration, fences)
            if line.kind == "unparsed" and page.recipes:
                trig = _trigger(it, page.recipes, names)
                if trig:
                    line = Line(line.source, [trig], 1, "action")
                    triggered = consume = True
            step.lines.append(line)
        page.steps.append(step)

    # A step with nothing to do is not part of the recording, and neither is the
    # optional epilogue quick starts end with ("Deploy to WSO2 Cloud" — after
    # the walkthrough, and it needs a cloud account). It is noted on the card.
    epilogue = [s for s in page.steps if EPILOGUE.search(s.title)]
    if epilogue and len(epilogue) < len(page.steps):
        page.notes_extra = [f"optional step not recorded: {s.title}" for s in epilogue]
        page.steps = [s for s in page.steps if s not in epilogue]
    page.steps = [s for s in page.steps if any(ln.kind != "info" for ln in s.lines)]
    for n, s in enumerate(page.steps, 1):
        s.n = n

    handled = set(page.setup_commands) | {
        m.group(1) for s in page.steps for ln in s.lines for w in ln.workflow
        for m in [re.match(r"Run the shell command `(.+)`", w)] if m}
    open_fences = [f for f in fences if _shell_command(f) not in handled
                   and (f[0] in SHELL_LANGS + ("cmd", "powershell"))]
    # Scan what the reader is told to DO (and the notes beside it), not the
    # intro prose: "files appearing in a folder or FTP server" describes the
    # feature, it does not ask for a server.
    instructions = "\n".join(it for _t, items in raw_steps for it in items)
    hard, soft = _blockers(FENCE_MARK_RE.sub("", instructions) + "\n" + "\n".join(admonitions)
                           + "\n" + prereq, open_fences, page.requires)
    for item in page.requires:
        started = any(re.search(prereqs.by_id(r)["match"], item, re.I) for r in page.recipes)
        if not started and not (page.inputs and KEYABLE.search(item)):
            page.manual_requires.append(item)
    covered = set()
    if page.recipes:
        covered.add("service")
    if not page.manual_requires:
        covered.add("prerequisite")
    if page.inputs:
        covered |= {"credentials", "account"}   # you have them; FlowCast is told
    if triggered:
        covered.add("external-ui")
    page.blockers = [b for b in hard if b not in covered]
    page.notes = soft

    lines = [ln for s in page.steps for ln in s.lines]
    acts = [ln for ln in lines if ln.kind != "info"]
    parsed = [ln for ln in acts if ln.kind == "action"]
    page.action_count = sum(ln.actions for ln in acts if ln.kind in ("action", "mixed"))
    page.coverage = round(len(parsed) / len(acts), 3) if acts else 0.0
    page.unparsed = [ln.manual or ln.source for ln in acts if ln.kind in ("unparsed", "mixed")][:12]

    if len(acts) < 3:
        page.verdict = "none"            # fewer than three things to do: not a walkthrough
    elif page.action_count < 3:
        page.verdict = "partial"
    elif page.coverage < 1.0:
        page.verdict = "partial"
    elif page.blockers:
        page.verdict = "setup"
    elif any(i["auto"] is None for i in page.inputs):
        page.verdict = "keys"
    elif page.recipes or page.inputs:
        page.verdict = "auto"
    elif page.coverage == 1.0:
        page.verdict = "ready"
    else:
        page.verdict = "partial"
    if page.steps:
        first = " ".join(w for ln in page.steps[0].lines for w in ln.workflow)
        page.starts_in_project = not re.search(
            r"Open WSO2 Integrator|Create New Integration|Create Integration", first, re.I)
    page.verified = VERIFIED_WORKFLOWS.get(page.path)
    return page


# ── workflow file ─────────────────────────────────────────────────────────────

def workflow_markdown(page: Page) -> str:
    """The page as a FlowCast workflow, in the shape of the recordings that
    already work (see workflows/build-integration-api.md)."""
    integration = None
    for s in page.steps:
        for ln in s.lines:
            for w in ln.workflow:
                m = re.match(r"Set \*\*Integration Name\*\* to `([^`]+)`", w)
                if m:
                    integration = m.group(1)
    out: list[str] = []
    offset = 0
    if page.starts_in_project:
        # The docs say "follow Create a New Integration first, then return
        # here" — so that is what the recording does.
        integration = integration or re.sub(r"[^A-Za-z0-9]", "", page.title.title())[:28] or "Demo"
        out += ["## Step 1: Create the integration\n",
                "1. Open WSO2 Integrator.",
                "2. Select **Skip for now**.",
                "3. Select **Create New Integration**.",
                f"4. Set **Integration Name** to `{integration}`.",
                f"5. Set **Project Name** to `{page.slug[:40]}`.",
                "6. Select **Create Integration**.",
                f"7. Select **{integration}**.", ""]
        out[1:1] = [f"{i}. Run the shell command `{c}` to prepare the prerequisites."
                    for i, c in enumerate(page.setup_commands, 1)]
        if page.setup_commands:   # renumber
            nums = iter(range(1, 100))
            out = [re.sub(r"^\d+\.", lambda _m: f"{next(nums)}.", ln) if re.match(r"^\d+\.", ln)
                   else ln for ln in out]
        offset = 1
    opened_handler: str | None = None
    for s in page.steps:
        out.append(f"## Step {s.n + offset}: {s.title}\n")
        body: list[str] = []
        # A handler added from "+ Add Handler" without a Save is created but not
        # opened; a step that then starts with "Select +" (in its flow) needs it
        # open first. Seen on the File-Driven quick start (Oct 3 run) and done
        # by hand in workflows/quick-start-file.md ("Select onModify again").
        first = next((w for ln in s.lines for w in ln.workflow), "")
        if opened_handler and re.match(r"^Select \*\*\+\*\*", first):
            body.append(f"Select **{opened_handler}**.")
        acts = [w for ln in s.lines for w in ln.workflow]
        opened_handler = None
        for a, b in zip(acts, acts[1:]):
            if re.match(r"^(?:.*\b)?select \*\*\+ Add Handler\*\*", a, re.I):
                m = re.match(r"^Select \*\*(on\w+)\*\*\.?$", b)
                if m and not any("**Save**" in x for x in acts[acts.index(b):]):
                    opened_handler = m.group(1)
        if s.n == 1 and not offset:
            body += [f"Run the shell command `{c}` to prepare the prerequisites."
                     for c in page.setup_commands]
        for ln in s.lines:
            if ln.kind == "info":
                note = re.sub(r"\s+", " ", ln.source).strip().lstrip("- ").rstrip(".") + "."
                # Kept for whoever reads the workflow — but a note that the
                # parser could still read as an action ("…and select **Publish
                # message**", absorbed by a trigger) must be invisible to it.
                if _parse(note):
                    note = f"<!-- note: {note.replace('<', '‹').replace('>', '›')} -->"
                body.append(note)
                continue
            if ln.kind == "unparsed":
                # A checkpoint the parser ignores (HTML is stripped) and
                # tools/autopilot.py stops at, handing you the doc's own words.
                text = re.sub(r"\s+", " ", re.sub(r"[*`]", "", ln.source)).strip().lstrip("- ")
                body.append(f"<!-- manual: {text.replace('<', '‹').replace('>', '›')} -->")
                continue
            if ln.kind == "mixed":
                body += [re.sub(r"\s+", " ", w).strip() for w in ln.workflow]
                text = re.sub(r"\s+", " ", ln.manual).strip()
                body.append(f"<!-- manual: {text.replace('<', '‹').replace('>', '›')} -->")
                continue
            for w in ln.workflow:
                w = re.sub(r"\s+", " ", w).strip()
                if re.match(r"^Select \*\*Run\*\*\.?$", w):
                    w = "Select **Run** in the toolbar."
                # File Integration is the last section of the Artifacts page and
                # starts below the fold on a laptop screen. (The parser's
                # "under" rule would swallow a "Scroll down and …" prefix, so the
                # scope is dropped to keep the scroll.)
                w = re.sub(r"^Select (\*\*[^*]+\*\*) under \*\*File Integration\*\*\.?$",
                           r"Scroll down and select \1.", w)
                body.append(w)
                if re.match(r"^Open WSO2 Integrator", w, re.I):
                    body.append("Select **Skip for now**.")
        # Timing the recorder needs and the docs leave implicit (the same dwell
        # the hand-tuned workflows/build-event-integration.md uses): give a
        # started integration time to come up before anything is sent to it,
        # and keep the result on screen after the step's last action.
        runs = [i for i, b in enumerate(body) if re.search(r"\*\*(Run|Execute|Send|Test)\*\*", b)]
        if runs and not any(b.startswith("Wait ") for b in body):
            acts = [i for i, b in enumerate(body) if _parse(b)]
            last = max(acts)
            after = [i for i in acts if i > runs[0]]
            if after and re.search(r"\*\*Run\*\*", body[runs[0]]) and \
                    body[after[0]].startswith("Run the shell command"):
                body.insert(runs[0] + 1, "Wait 10 seconds.")
                last += 1
            body.insert(last + 1, "Wait 8 seconds.")
        out += [f"{i}. {b}" for i, b in enumerate(body, 1)]
        out.append("")
    if integration:
        out = [ln.replace("Select **your integration**", f"Select **{integration}**") for ln in out]
    return "\n".join(out).rstrip() + "\n"


# ── whole catalog ─────────────────────────────────────────────────────────────

def build(docs_root: Path, write_workflows: bool = True) -> dict:
    pages: list[Page] = []
    for p in sorted(docs_root.rglob("*")):
        if p.suffix not in (".md", ".mdx") or "/_" in str(p):
            continue
        pages.append(analyse(p, docs_root))

    seen: dict[str, int] = {}
    for pg in pages:                                   # unique slugs
        if pg.slug in seen:
            seen[pg.slug] += 1
            pg.slug = f"{pg.slug}-{seen[pg.slug]}"
        else:
            seen[pg.slug] = 1

    if write_workflows:
        WORKFLOW_DIR.mkdir(parents=True, exist_ok=True)
        for old in WORKFLOW_DIR.glob("*.md"):
            old.unlink()
        for pg in pages:
            if pg.verdict != "none":
                f = WORKFLOW_DIR / f"{pg.slug}.md"
                f.write_text(f"{GENERATED_MARK} {pg.url} -->\n\n" + workflow_markdown(pg))
                (WORKFLOW_DIR / f"{pg.slug}.meta.json").write_text(json.dumps({
                    "title": pg.title, "time": pg.time, "build": pg.build,
                    "links": [["Documentation", pg.url]], "slug": pg.slug}, indent=2))
                pg.workflow_file = str(f.relative_to(ROOT))

    counts = {v: sum(1 for p in pages if p.verdict == v) for v in VERDICTS}
    by_area: dict[str, dict[str, int]] = {}
    for p in pages:
        a = by_area.setdefault(p.area.split(" · ")[0], {v: 0 for v in VERDICTS})
        a[p.verdict] += 1
    blocker_counts: dict[str, int] = {}
    for p in pages:
        if p.verdict == "setup":
            for b in p.blockers:
                blocker_counts[b] = blocker_counts.get(b, 0) + 1
    return {
        "version": 1,
        "source": DOCS_REPO,
        "site": DOCS_SITE,
        "commit": source_commit(),
        "summary": {"total": len(pages), "walkthroughs": len(pages) - counts["none"],
                    **counts, "verified": sum(1 for p in pages if p.verified),
                    "by_area": by_area, "setup_blockers": blocker_counts},
        "pages": [asdict(p) for p in pages],
    }


def load() -> dict:
    return json.loads(CATALOG.read_text()) if CATALOG.exists() else {}
