#!/usr/bin/env python3
"""Auto-generated by FlowCast — run to replay all steps without recording."""
from __future__ import annotations
import sys
from pathlib import Path

# Allow running from the output directory
sys.path.insert(0, str(Path(__file__).parent.parent.parent))

from dotenv import load_dotenv
load_dotenv()

from src import runner


def _run(action):
    resolved = runner.resolve(action)
    if resolved.get('_skip'):
        return
    runner.fire(resolved)
    if resolved['action'] not in ('open_app', 'wait', 'hotkey'):
        runner.wait_ui_change()
    runner.wait_ui_settle()


# ──────────────────────────────────────────────────────────
# Step 1: Create a New Integration Project
# ──────────────────────────────────────────────────────────
_run({'action': 'open_app', 'app_name': 'WSO2 Integrator', 'app_path': '/Users/sachindu/Applications/WSO2 Integrator.app'})
_run({'action': 'click', 'target': 'Create'})
_run({'action': 'type', 'field_target': 'Integration Name', 'value': 'sales-manager'})
_run({'action': 'click', 'target': 'Browse'})
_run({'action': 'click', 'target': 'Open'})
_run({'action': 'click', 'target': 'Create Integration'})

# ──────────────────────────────────────────────────────────
# Step 2: Add an HTTP Service Artifact
# ──────────────────────────────────────────────────────────
_run({'action': 'click', 'target': 'sales-manager'})
_run({'action': 'click', 'target': '+ Add Artifact'})
_run({'action': 'click', 'target': 'HTTP Service'})
_run({'action': 'type', 'field_target': 'Service Base Path', 'value': '/salesorder'})
_run({'action': 'click', 'target': 'Create'})

# ──────────────────────────────────────────────────────────
# Step 3: Configure the HTTP Service and Add a Resource
# ──────────────────────────────────────────────────────────
_run({'action': 'click', 'target': 'Add Resources'})
_run({'action': 'click', 'target': 'POST'})
_run({'action': 'type', 'field_target': 'Resource Path', 'value': '.'})
_run({'action': 'click', 'target': 'Save'})

# ──────────────────────────────────────────────────────────
# Step 4: Open the Resource Flow and Add the SAP Connector
# ──────────────────────────────────────────────────────────
_run({'action': 'click', 'target': '+'})
_run({'action': 'click', 'target': 'Add Connection'})
_run({'action': 'type', 'field_target': 'Connection Name', 'value': 'api_sales_order_srv'})
_run({'action': 'click', 'target': 'Api_sales_order_srv'})
_run({'action': 'click', 'target': 'Add'})

# ──────────────────────────────────────────────────────────
# Step 5: Configure the SAP Connector Connection
# ──────────────────────────────────────────────────────────
_run({'action': 'type', 'field_target': 'Auth', 'value': 'WS02_MAIN_DEV'})
_run({'action': 'type', 'field_target': 'Password', 'value': 'your-sap-password'})
_run({'action': 'type', 'field_target': 'Hostname', 'value': 'my401785.s4hana.cloud.sap'})
_run({'action': 'click', 'target': 'Save'})

# ──────────────────────────────────────────────────────────
# Step 6: Define the Request Payload
# ──────────────────────────────────────────────────────────
_run({'action': 'click', 'target': 'Configure'})
_run({'action': 'click', 'target': 'Import'})
_run({'action': 'type', 'field_target': 'Data Format', 'value': 'JSON'})
_run({'action': 'click', 'target': 'Save'})

# ──────────────────────────────────────────────────────────
# Step 7: Select the Create Sales Order Operation
# ──────────────────────────────────────────────────────────
_run({'action': 'click', 'target': '+'})
_run({'action': 'click', 'target': 'apiSalesOrderSrvClient'})
_run({'action': 'click', 'target': 'Create A Sales Order'})

# ──────────────────────────────────────────────────────────
# Step 8: Map the Payload to the SAP API Fields
# ──────────────────────────────────────────────────────────
_run({'action': 'type', 'field_target': 'SalesOrderType', 'value': 'OR'})
_run({'action': 'type', 'field_target': 'SalesOrganization', 'value': '1710'})
_run({'action': 'type', 'field_target': 'DistributionChannel', 'value': '10'})
_run({'action': 'type', 'field_target': 'OrganizationDivision', 'value': '00'})
_run({'action': 'click', 'target': 'Save'})

# ──────────────────────────────────────────────────────────
# Step 9: Return the SAP Response
# ──────────────────────────────────────────────────────────
_run({'action': 'click', 'target': '+'})
_run({'action': 'click', 'target': 'Return'})
_run({'action': 'type', 'field_target': 'Return expression', 'value': 'apiSalesOrderSrvASalesorderwrapper.toJson()'})
_run({'action': 'click', 'target': 'Save'})

# ──────────────────────────────────────────────────────────
# Step 10: Run and Test the Integration
# ──────────────────────────────────────────────────────────
_run({'action': 'click', 'target': 'Run'})
